local Register = LibCodesCommonCode.RegisterString

Register("SI_LCK_SCAN_START"                , "Scanning item table; this occurs only once per major game update.")
Register("SI_LCK_SCAN_COMPLETE"             , "Scan complete.")
Register("SI_LCK_SCAN_CONSOLE"              , "|cFF0000Scanning is unsupported for console; please update to a newer version with pre-scanned data.|r")
Register("SI_LCK_SCAN_RESEARCH_BAD_TRAITS"  , "|cFF0000Research trait count appears to have unexpectedly changed.|r")
Register("SI_LCK_SCAN_RESEARCH_BAD_SIG"     , "|cFF0000Research indices appear to have unexpectedly changed.|r")

Register("SI_LCK_SETTINGS_CHATCOMMAND"      , "This addon settings panel can also be accessed via the |c00CCFF/lck|r chat command.")

Register("SI_LCK_SETTINGS_SERVER"           , "Server")
SI_LCK_SETTINGS_ACCOUNT = SI_CURRENCYLOCATION3
SI_LCK_SETTINGS_CHARACTER = SI_CURRENCYLOCATION0

Register("SI_LCK_SETTINGS_SYSTEM_DEFLABEL"  , "<Global Defaults>")
Register("SI_LCK_SETTINGS_SERVER_DEFLABEL"  , "<Server Defaults>")
Register("SI_LCK_SETTINGS_ACCOUNT_DEFLABEL" , "<Account Defaults>")

Register("SI_LCK_SETTINGS_USE_DEFAULT"      , "Use default")

Register("SI_LCK_SETTINGS_TRACKING1"        , "Do not track")
Register("SI_LCK_SETTINGS_TRACKING2"        , "Track low quality")
Register("SI_LCK_SETTINGS_TRACKING3"        , "Track medium quality")
Register("SI_LCK_SETTINGS_TRACKING4"        , "Track all")

Register("SI_LCK_SETTINGS_PRIORITY"         , "Priority Rank")
Register("SI_LCK_SETTINGS_PRIORITY_HELP"    , "Multiple characters can share the same priority rank; characters with the same priority rank are ranked by seniority, with older characters given precedence over newer characters.")

Register("SI_LCK_SETTINGS_EXPORT"           , "Select for Export")

Register("SI_LCK_SETTINGS_MAIN_SECTION"     , "Tracking and Priority")
Register("SI_LCK_SETTINGS_RANKING_PREVIEW"  , "Current character ranking order")
Register("SI_LCK_SETTINGS_SYSTEM_DEFAULTS"  , "These system-wide defaults will apply to every character unless overridden at the server, account, or character level:")
Register("SI_LCK_SETTINGS_SERVER_DEFAULTS"  , "These server-wide defaults will apply to every character on |cFFFF00<<1>>|r unless overridden at the account or character level:")
Register("SI_LCK_SETTINGS_ACCOUNT_DEFAULTS" , "These account-wide defaults will apply to every character belonging to |cFFFF00<<1>>|r on |cFFFF00<<2>>|r unless overridden at the character level:")
Register("SI_LCK_SETTINGS_CHAR_SPECIFC"     , "These settings will apply to |cFFFF00<<1>>|r on |cFFFF00<<2>>|r:")

Register("SI_LCK_SETTINGS_SHARE_SECTION"    , "Share Data")
Register("SI_LCK_SETTINGS_SHARE_CAPTION"    , "Export and copy, or paste and import, to share data")
Register("SI_LCK_SETTINGS_SHARE_EXPORTC"    , "Export Current")
Register("SI_LCK_SETTINGS_SHARE_EXPORTCT"   , "Export knowledge data for the current character")
Register("SI_LCK_SETTINGS_SHARE_EXPORTA"    , "Export All")
Register("SI_LCK_SETTINGS_SHARE_EXPORTAT"   , "Export knowledge data for every enabled character")
Register("SI_LCK_SETTINGS_SHARE_EXPORTS"    , "Export Selected (%d)")
Register("SI_LCK_SETTINGS_SHARE_EXPORTST"   , "Export knowledge data for characters with \"Select for Export\" enabled")
Register("SI_LCK_SETTINGS_SHARE_IMPORT"     , "Import")
Register("SI_LCK_SETTINGS_SHARE_CLEAR"      , "Clear")

Register("SI_LCK_SETTINGS_RESET_SECTION"    , "Reset Data")
Register("SI_LCK_SETTINGS_RESET_WARNING"    , "This will reset all settings, delete all data associated with LibCharacterKnowledge, and reload the UI.")

Register("SI_LCK_SETTINGS_NOSAVE_SECTION"   , "Excluded Accounts")
Register("SI_LCK_SETTINGS_NOSAVE_CAPTION"   , "List of account names, separated by commas, to exclude from being saved")

Register("SI_LCK_SHARE_EXPORT_LIMIT"        , "Skipped [<<1>>/<<2>>]; data limit reached.")
Register("SI_LCK_SHARE_IMPORT_STALE"        , "Skipped [<<1>>/<<2>>]; current data is more recent.")
Register("SI_LCK_SHARE_IMPORT_API"          , "Skipped [<<1>>/<<2>>]; imported data was generated by a different version of the game.")
Register("SI_LCK_SHARE_IMPORT_DONE"         , "Imported [<<1>>/<<2>>]. (<<3>>)")
Register("SI_LCK_SHARE_IMPORT_INVALID"      , "Aborting import; corrupted data encountered.")
Register("SI_LCK_SHARE_IMPORT_BADVERSION"   , "Imported data was encoded by an incompatible version of LibCharacterKnowledge; please ensure that both users have updated to the latest version of LibCharacterKnowledge.")
Register("SI_LCK_SHARE_IMPORT_NEWCHARACTER" , "You have imported one or more new characters that did not previously exist in the database; |c00CCFF/reloadui|r may be necessary for newly-added characters to appear in menus and settings.")
Register("SI_LCK_SHARE_IMPORT_TALLY"        , "<<1>> characters imported.")
