ssi = {}
ssi.appName = "SkyrimStyleUI"

local ADDON_VERSION = "1.34"

function ssivanilla()

		---- Interface ----

		RedirectTexture("esoui/art/miscellaneous/progressbar_frame.dds", "esoui/art/miscellaneous/progressbar_frame.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_crowncrates_up.dds", "/esoui/art/mainmenu/menubar_crowncrates_up.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_crowncrates_down.dds", "/esoui/art/mainmenu/menubar_crowncrates_down.dds")
		RedirectTexture("/SkyrimStyleUI/media/compass_left.dds", "/SkyrimStyleUI/media/blank_left.dds")
		RedirectTexture("/SkyrimStyleUI/media/compass_right.dds", "/SkyrimStyleUI/media/blank_right.dds")
		RedirectTexture("esoui/art/compass/gamepad/gp_compass.dds", "esoui/art/compass/gamepad/gp_compass.dds")
		RedirectTexture("/SkyrimStyleUI/media/compass.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("esoui/art/miscellaneous/centerscreen_left.dds", "esoui/art/miscellaneous/centerscreen_left.dds")
		RedirectTexture("esoui/art/miscellaneous/listitem_backdrop.dds", "esoui/art/miscellaneous/listitem_backdrop.dds")
		RedirectTexture("esoui/art/miscellaneous/bottom_bar.dds", "esoui/art/miscellaneous/bottom_bar.dds")
		RedirectTexture("esoui/art/miscellaneous/top_bar.dds", "esoui/art/miscellaneous/top_bar.dds")
		RedirectTexture("esoui/art/miscellaneous/centerscreen_right.dds", "esoui/art/miscellaneous/centerscreen_right.dds")
		RedirectTexture("esoui/art/interaction/conversation_textbg.dds", "esoui/art/interaction/conversation_textbg.dds")
		RedirectTexture("esoui/art/miscellaneous/listitem_highlight.dds", "esoui/art/miscellaneous/listitem_highlight.dds")
		RedirectTexture("esoui/art/miscellaneous/listitem_selectedhighlight.dds", "esoui/art/miscellaneous/listitem_selectedhighlight.dds")
		RedirectTexture("esoui/art/tooltips/ui-tooltipcenter.dds", "esoui/art/tooltips/ui-tooltipcenter.dds")
		RedirectTexture("esoui/art/loot/loot_windowbg.dds", "esoui/art/loot/loot_windowbg.dds")
		RedirectTexture("esoui/art/tooltips/ui-border.dds", "esoui/art/tooltips/ui-border.dds")
		RedirectTexture("esoui/art/tooltips/ui-border-red.dds", "esoui/art/tooltips/ui-border-red.dds")
		RedirectTexture("esoui/art/tooltips/tooltip_equippedlabel_bg.dds", "esoui/art/tooltips/tooltip_equippedlabel_bg.dds")
		RedirectTexture("esoui/art/tooltips/munge_overlay.dds", "esoui/art/tooltips/munge_overlay.dds")
		RedirectTexture("esoui/art/miscellaneous/interactkeyframe_center.dds", "esoui/art/miscellaneous/interactkeyframe_center.dds")
		RedirectTexture("esoui/art/miscellaneous/interactkeyframe_edge.dds", "esoui/art/miscellaneous/interactkeyframe_edge.dds")
		RedirectTexture("esoui/art/stealth/stealth_64.dds", "esoui/art/stealth/stealth_64.dds")
		RedirectTexture("esoui/art/reticle/reticleanim.dds", "esoui/art/reticle/reticleanim.dds")
		RedirectTexture("esoui/art/compass/compass.dds", "esoui/art/compass/compass.dds")
		RedirectTexture("esoui/art/compass/area2frameanim_assisted_endcap.dds", "esoui/art/compass/area2frameanim_assisted_endcap.dds")
		RedirectTexture("esoui/art/compass/area2frameanim_standard_endcap.dds", "esoui/art/compass/area2frameanim_standard_endcap.dds")
		RedirectTexture("esoui/art/compass/areapin2frame_ends.dds", "esoui/art/compass/areapin2frame_ends.dds")
		RedirectTexture("esoui/art/compass/area2frameanim_assisted_center.dds", "esoui/art/compass/area2frameanim_assisted_center.dds")
		RedirectTexture("esoui/art/compass/area2frameanim_standard_center.dds", "esoui/art/compass/area2frameanim_standard_center.dds")
		RedirectTexture("esoui/art/compass/area2frameanim_centers.dds", "esoui/art/compass/area2frameanim_centers.dds")
		RedirectTexture("esoui/art/actionbar/abilityframe64_down.dds", "esoui/art/actionbar/abilityframe64_down.dds")
		RedirectTexture("esoui/art/actionbar/abilityframe64_up.dds", "esoui/art/actionbar/abilityframe64_up.dds")
		RedirectTexture("esoui/art/quickslots/quickslot_mapping_bg.dds", "esoui/art/quickslots/quickslot_mapping_bg.dds")
		RedirectTexture("esoui/art/quickslots/quickslot_highlight_blob.dds", "esoui/art/quickslots/quickslot_highlight_blob.dds")
		RedirectTexture("esoui/art/quickslots/quickslot_emptyslot.dds", "esoui/art/quickslots/quickslot_emptyslot.dds")
		RedirectTexture("esoui/art/actionbar/quickslotbg.dds", "esoui/art/actionbar/quickslotbg.dds")
		RedirectTexture("esoui/art/quickslots/quickslot_dragslot.dds", "esoui/art/quickslots/quickslot_dragslot.dds")
		RedirectTexture("esoui/art/hud/radialmenu_bg_unselected.dds", "esoui/art/hud/radialmenu_bg_unselected.dds")
		RedirectTexture("esoui/art/hud/radialmenu_bg.dds", "esoui/art/hud/radialmenu_bg.dds")
		RedirectTexture("esoui/art/miscellaneous/centerscreen_indexarea_left.dds", "esoui/art/miscellaneous/centerscreen_indexarea_left.dds")
		RedirectTexture("esoui/art/miscellaneous/centerscreen_indexarea_right.dds", "esoui/art/miscellaneous/centerscreen_indexarea_right.dds")	

		---- Icons ----

		RedirectTexture("esoui/art/crafting/provisioner_indexicon_furnishings_up.dds", "esoui/art/crafting/provisioner_indexicon_furnishings_up.dds")
		RedirectTexture("esoui/art/crafting/provisioner_indexicon_furnishings_down.dds", "esoui/art/crafting/provisioner_indexicon_furnishings_down.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_inventory_up.dds", "esoui/art/mainmenu/menubar_inventory_up.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_character_up.dds", "esoui/art/mainmenu/menubar_character_up.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_ava_up.dds", "esoui/art/mainmenu/menubar_ava_up.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_collections_up.dds", "esoui/art/mainmenu/menubar_collections_up.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_group_up.dds", "esoui/art/mainmenu/menubar_group_up.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_guilds_up.dds", "esoui/art/mainmenu/menubar_guilds_up.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_journal_up.dds", "esoui/art/mainmenu/menubar_journal_up.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_mail_up.dds", "esoui/art/mainmenu/menubar_mail_up.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_map_up.dds", "esoui/art/mainmenu/menubar_map_up.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_market_up.dds", "esoui/art/mainmenu/menubar_market_up.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_notifications_up.dds", "esoui/art/mainmenu/menubar_notifications_up.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_skills_up.dds", "esoui/art/mainmenu/menubar_skills_up.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_social_up.dds", "esoui/art/mainmenu/menubar_social_up.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_champion_up.dds", "esoui/art/mainmenu/menubar_champion_up.dds")
		RedirectTexture("esoui/art/menubar/menubar_help_up.dds", "esoui/art/menubar/menubar_help_up.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_inventory_down.dds", "esoui/art/mainmenu/menubar_inventory_down.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_character_down.dds", "esoui/art/mainmenu/menubar_character_down.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_ava_down.dds", "esoui/art/mainmenu/menubar_ava_down.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_collections_down.dds", "esoui/art/mainmenu/menubar_collections_down.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_group_down.dds", "esoui/art/mainmenu/menubar_group_down.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_guilds_down.dds", "esoui/art/mainmenu/menubar_guilds_down.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_journal_down.dds", "esoui/art/mainmenu/menubar_journal_down.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_mail_down.dds", "esoui/art/mainmenu/menubar_mail_down.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_map_down.dds", "esoui/art/mainmenu/menubar_map_down.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_market_down.dds", "esoui/art/mainmenu/menubar_market_down.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_notifications_down.dds", "esoui/art/mainmenu/menubar_notifications_down.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_skills_down.dds", "esoui/art/mainmenu/menubar_skills_down.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_social_down.dds", "esoui/art/mainmenu/menubar_social_down.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_champion_down.dds", "esoui/art/mainmenu/menubar_champion_down.dds")
		RedirectTexture("esoui/art/menubar/menubar_help_down.dds", "esoui/art/menubar/menubar_help_down.dds")

		RedirectTexture("esoui/art/mainmenu/menubar_inventory_disabled.dds", "esoui/art/mainmenu/menubar_inventory_disabled.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_character_disabled.dds", "esoui/art/mainmenu/menubar_character_disabled.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_ava_disabled.dds", "esoui/art/mainmenu/menubar_ava_disabled.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_collections_disabled.dds", "esoui/art/mainmenu/menubar_collections_disabled.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_group_disabled.dds", "esoui/art/mainmenu/menubar_group_disabled.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_guilds_disabled.dds", "esoui/art/mainmenu/menubar_guilds_disabled.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_journal_disabled.dds", "oesoui/art/mainmenu/menubar_journal_disabled.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_mail_disabled.dds", "esoui/art/mainmenu/menubar_mail_disabled.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_map_disabled.dds", "esoui/art/mainmenu/menubar_map_disabled.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_market_disabled.dds", "esoui/art/mainmenu/menubar_market_disabled.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_notifications_disabled.dds", "esoui/art/mainmenu/menubar_notifications_disabled.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_skills_disabled.dds", "esoui/art/mainmenu/menubar_skills_disabled.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_social_disabled.dds", "esoui/art/mainmenu/menubar_social_disabled.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_champion_disabled.dds", "esoui/art/mainmenu/menubar_champion_disabled.dds")
		RedirectTexture("esoui/art/menubar/menubar_help_disabled.dds", "esoui/art/menubar/menubar_help_disabled.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_inventory_over.dds", "esoui/art/mainmenu/menubar_inventory_over.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_character_over.dds", "esoui/art/mainmenu/menubar_character_over.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_ava_over.dds", "esoui/art/mainmenu/menubar_ava_over.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_collections_over.dds", "esoui/art/mainmenu/menubar_collections_over.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_group_over.dds", "esoui/art/mainmenu/menubar_group_over.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_guilds_over.dds", "esoui/art/mainmenu/menubar_guilds_over.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_journal_over.dds", "oesoui/art/mainmenu/menubar_journal_over.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_mail_over.dds", "esoui/art/mainmenu/menubar_mail_over.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_map_over.dds", "esoui/art/mainmenu/menubar_map_over.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_market_over.dds", "esoui/art/mainmenu/menubar_market_over.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_notifications_over.dds", "esoui/art/mainmenu/menubar_notifications_over.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_skills_over.dds", "esoui/art/mainmenu/menubar_skills_over.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_social_over.dds", "esoui/art/mainmenu/menubar_social_over.dds")
		RedirectTexture("esoui/art/mainmenu/menubar_champion_over.dds", "esoui/art/mainmenu/menubar_champion_over.dds")
		RedirectTexture("esoui/art/menubar/menubar_help_over.dds", "esoui/art/menubar/menubar_help_over.dds")

		RedirectTexture("esoui/art/inventory/inventory_tabicon_all_up.dds", "esoui/art/inventory/inventory_tabicon_all_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_armor_up.dds", "esoui/art/inventory/inventory_tabicon_armor_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_consumables_up.dds", "esoui/art/inventory/inventory_tabicon_consumables_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_crafting_up.dds", "esoui/art/inventory/inventory_tabicon_crafting_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_quest_up.dds", "esoui/art/inventory/inventory_tabicon_quest_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_misc_up.dds", "esoui/art/inventory/inventory_tabicon_misc_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_junk_up.dds", "esoui/art/inventory/inventory_tabicon_junk_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_weapons_up.dds", "esoui/art/inventory/inventory_tabicon_weapons_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_junk_up.dds", "esoui/art/inventory/inventory_tabicon_junk_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_weapons_up.dds", "esoui/art/inventory/inventory_tabicon_weapons_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_all_down.dds", "esoui/art/inventory/inventory_tabicon_all_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_armor_down.dds", "esoui/art/inventory/inventory_tabicon_armor_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_consumables_down.dds", "esoui/art/inventory/inventory_tabicon_consumables_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_crafting_down.dds", "esoui/art/inventory/inventory_tabicon_crafting_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_quest_down.dds", "esoui/art/inventory/inventory_tabicon_quest_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_misc_down.dds", "esoui/art/inventory/inventory_tabicon_misc_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_junk_down.dds", "esoui/art/inventory/inventory_tabicon_junk_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_weapons_down.dds", "esoui/art/inventory/inventory_tabicon_weapons_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_junk_down.dds", "esoui/art/inventory/inventory_tabicon_junk_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_weapons_down.dds", "esoui/art/inventory/inventory_tabicon_weapons_down.dds")

		RedirectTexture("/esoui/art/mainmenu/menubar_crowncrates_disabled.dds", "/esoui/art/mainmenu/menubar_crowncrates_disabled.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_crowncrates_over.dds", "/esoui/art/mainmenu/menubar_crowncrates_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_all_disabled.dds", "esoui/art/inventory/inventory_tabicon_all_disabled.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_armor_disabled.dds", "esoui/art/inventory/inventory_tabicon_armor_disabled.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_consumables_disabled.dds", "esoui/art/inventory/inventory_tabicon_consumables_disabled.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_crafting_disabled.dds", "esoui/art/inventory/inventory_tabicon_crafting_disabled.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_quest_disabled.dds", "esoui/art/inventory/inventory_tabicon_quest_disabled.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_misc_disabled.dds", "esoui/art/inventory/inventory_tabicon_misc_disabled.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_junk_disabled.dds", "esoui/art/inventory/inventory_tabicon_junk_disabled.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_weapons_disabled.dds", "esoui/art/inventory/inventory_tabicon_weapons_disabled.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_junk_disabled.dds", "esoui/art/inventory/inventory_tabicon_junk_disabled.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_weapons_disabled.dds", "esoui/art/inventory/inventory_tabicon_weapons_disabled.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_all_over.dds", "esoui/art/inventory/inventory_tabicon_all_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_armor_over.dds", "esoui/art/inventory/inventory_tabicon_armor_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_consumables_over.dds", "esoui/art/inventory/inventory_tabicon_consumables_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_crafting_over.dds", "esoui/art/inventory/inventory_tabicon_crafting_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_quest_over.dds", "esoui/art/inventory/inventory_tabicon_quest_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_misc_over.dds", "esoui/art/inventory/inventory_tabicon_misc_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_junk_over.dds", "esoui/art/inventory/inventory_tabicon_junk_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_weapons_over.dds", "esoui/art/inventory/inventory_tabicon_weapons_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_junk_over.dds", "esoui/art/inventory/inventory_tabicon_junk_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_weapons_over.dds", "esoui/art/inventory/inventory_tabicon_weapons_over.dds")

		RedirectTexture("esoui/art/bank/bank_tabicon_gold_up.dds", "esoui/art/bank/bank_tabicon_gold_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_items_up.dds", "esoui/art/inventory/inventory_tabicon_items_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_up.dds", "esoui/art/inventory/inventory_tabicon_craftbag_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_quickslot_up.dds", "esoui/art/inventory/inventory_tabicon_quickslot_up.dds")
		RedirectTexture("esoui/art/bank/bank_tabicon_gold_down.dds", "esoui/art/bank/bank_tabicon_gold_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_items_down.dds", "esoui/art/inventory/inventory_tabicon_items_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_down.dds", "esoui/art/inventory/inventory_tabicon_craftbag_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_quickslot_down.dds", "esoui/art/inventory/inventory_tabicon_quickslot_down.dds")

		RedirectTexture("esoui/art/crafting/provisioner_indexicon_furnishings_disabled.dds", "esoui/art/crafting/provisioner_indexicon_furnishings_disabled.dds")
		RedirectTexture("esoui/art/crafting/provisioner_indexicon_furnishings_over.dds", "esoui/art/crafting/provisioner_indexicon_furnishings_over.dds")
		RedirectTexture("esoui/art/bank/bank_tabicon_gold_disabled.dds", "esoui/art/bank/bank_tabicon_gold_disabled.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_items_disabled.dds", "esoui/art/inventory/inventory_tabicon_items_disabled.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_disabled.dds", "esoui/art/inventory/inventory_tabicon_craftbag_disabled.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_quickslot_disabled.dds", "esoui/art/inventory/inventory_tabicon_quickslot_disabled.dds")
		RedirectTexture("esoui/art/bank/bank_tabicon_gold_over.dds", "esoui/art/bank/bank_tabicon_gold_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_items_over.dds", "esoui/art/inventory/inventory_tabicon_items_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_over.dds", "esoui/art/inventory/inventory_tabicon_craftbag_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_quickslot_over.dds", "esoui/art/inventory/inventory_tabicon_quickslot_over.dds")

		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_alchemy_up.dds", "esoui/art/inventory/inventory_tabicon_craftbag_alchemy_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_blacksmithing_up.dds", "esoui/art/inventory/inventory_tabicon_craftbag_blacksmithing_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_clothing_up.dds", "esoui/art/inventory/inventory_tabicon_craftbag_clothing_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_alchemy_up.dds", "esoui/art/inventory/inventory_tabicon_craftbag_alchemy_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_enchanting_up.dds", "esoui/art/inventory/inventory_tabicon_craftbag_enchanting_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_fishing_up.dds", "esoui/art/inventory/inventory_tabicon_craftbag_fishing_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_itemtrait_up.dds", "esoui/art/inventory/inventory_tabicon_craftbag_itemtrait_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_provisioning_up.dds", "esoui/art/inventory/inventory_tabicon_craftbag_provisioning_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_alchemy_up.dds", "esoui/art/inventory/inventory_tabicon_craftbag_alchemy_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_stylematerial_up.dds", "esoui/art/inventory/inventory_tabicon_craftbag_stylematerial_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_woodworking_up.dds", "esoui/art/inventory/inventory_tabicon_craftbag_woodworking_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_alchemy_down.dds", "esoui/art/inventory/inventory_tabicon_craftbag_alchemy_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_blacksmithing_down.dds", "esoui/art/inventory/inventory_tabicon_craftbag_blacksmithing_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_clothing_down.dds", "esoui/art/inventory/inventory_tabicon_craftbag_clothing_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_alchemy_down.dds", "esoui/art/inventory/inventory_tabicon_craftbag_alchemy_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_enchanting_down.dds", "esoui/art/inventory/inventory_tabicon_craftbag_enchanting_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_fishing_down.dds", "esoui/art/inventory/inventory_tabicon_craftbag_fishing_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_itemtrait_down.dds", "esoui/art/inventory/inventory_tabicon_craftbag_itemtrait_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_provisioning_down.dds", "esoui/art/inventory/inventory_tabicon_craftbag_provisioning_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_alchemy_down.dds", "esoui/art/inventory/inventory_tabicon_craftbag_alchemy_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_stylematerial_down.dds", "esoui/art/inventory/inventory_tabicon_craftbag_stylematerial_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_woodworking_down.dds", "esoui/art/inventory/inventory_tabicon_craftbag_woodworking_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_alchemy_over.dds", "esoui/art/inventory/inventory_tabicon_craftbag_alchemy_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_blacksmithing_over.dds", "esoui/art/inventory/inventory_tabicon_craftbag_blacksmithing_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_clothing_over.dds", "esoui/art/inventory/inventory_tabicon_craftbag_clothing_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_alchemy_over.dds", "esoui/art/inventory/inventory_tabicon_craftbag_alchemy_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_enchanting_over.dds", "esoui/art/inventory/inventory_tabicon_craftbag_enchanting_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_fishing_over.dds", "esoui/art/inventory/inventory_tabicon_craftbag_fishing_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_itemtrait_over.dds", "esoui/art/inventory/inventory_tabicon_craftbag_itemtrait_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_provisioning_over.dds", "esoui/art/inventory/inventory_tabicon_craftbag_provisioning_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_alchemy_over.dds", "esoui/art/inventory/inventory_tabicon_craftbag_alchemy_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_stylematerial_over.dds", "esoui/art/inventory/inventory_tabicon_craftbag_stylematerial_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_woodworking_over.dds", "esoui/art/inventory/inventory_tabicon_craftbag_woodworking_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_jewelrycrafting_up.dds", "esoui/art/inventory/inventory_tabicon_craftbag_jewelrycrafting_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_jewelrycrafting_down.dds", "esoui/art/inventory/inventory_tabicon_craftbag_jewelrycrafting_down.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_jewelrycrafting_over.dds", "esoui/art/inventory/inventory_tabicon_craftbag_jewelrycrafting_over.dds")
		RedirectTexture("esoui/art/inventory/inventory_currencytab_accountwide_up.dds", "oblivionstylehud/media/icons/inventory_currencytab_accountwide_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_currencytab_accountwide_down.dds", "oblivionstylehud/media/icons/inventory_currencytab_accountwide_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_currencytab_accountwide_over.dds", "oblivionstylehud/media/interface/ob_ui_blank.dds")
		RedirectTexture("esoui/art/inventory/inventory_currencytab_oncharacter_up.dds", "oblivionstylehud/media/icons/inventory_currencytab_oncharacter_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_currencytab_oncharacter_down.dds", "oblivionstylehud/media/icons/inventory_currencytab_oncharacter_up.dds")
		RedirectTexture("esoui/art/inventory/inventory_currencytab_oncharacter_over.dds", "oblivionstylehud/media/interface/ob_ui_blank.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_vanitypets_up.dds", "oblivionstylehud/media/icons/store_indexicon_vanitypets_up.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_vanitypets_down.dds", "oblivionstylehud/media/icons/store_indexicon_vanitypets_up.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_vanitypets_over.dds", "oblivionstylehud/media/interface/ob_ui_blank.dds")
		RedirectTexture("esoui/art/treeicons/collection_indexicon_assistants_up.dds", "oblivionstylehud/media/icons/collection_indexicon_assistants_up.dds")
		RedirectTexture("esoui/art/treeicons/collection_indexicon_assistants_down.dds", "oblivionstylehud/media/icons/collection_indexicon_assistants_up.dds")
		RedirectTexture("esoui/art/treeicons/collection_indexicon_assistants_over.dds", "oblivionstylehud/media/interface/ob_ui_blank.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_costumes_up.dds", "oblivionstylehud/media/icons/store_indexicon_costumes_up.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_costumes_down.dds", "oblivionstylehud/media/icons/store_indexicon_costumes_up.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_costumes_over.dds", "oblivionstylehud/media/interface/ob_ui_blank.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_trophy_up.dds", "oblivionstylehud/media/icons/store_indexicon_trophy_up.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_trophy_down.dds", "oblivionstylehud/media/icons/store_indexicon_trophy_up.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_trophy_over.dds", "oblivionstylehud/media/interface/ob_ui_blank.dds")


		---- Details ----

		RedirectTexture("esoui/art/characterwindow/gearslot_chest.dds", "esoui/art/characterwindow/gearslot_chest.dds")
		RedirectTexture("esoui/art/characterwindow/gearslot_head.dds", "esoui/art/characterwindow/gearslot_head.dds")
		RedirectTexture("esoui/art/characterwindow/gearslot_hands.dds", "esoui/art/characterwindow/gearslot_hands.dds")
		RedirectTexture("esoui/art/characterwindow/gearslot_legs.dds", "esoui/art/characterwindow/gearslot_legs.dds")
		RedirectTexture("esoui/art/characterwindow/gearslot_feet.dds", "esoui/art/characterwindow/gearslot_feet.dds")
		RedirectTexture("esoui/art/characterwindow/gearslot_belt.dds", "esoui/art/characterwindow/gearslot_belt.dds")
		RedirectTexture("esoui/art/characterwindow/gearslot_shoulders.dds", "esoui/art/characterwindow/gearslot_shoulders.dds")
		RedirectTexture("esoui/art/characterwindow/gearslot_costume.dds", "esoui/art/characterwindow/gearslot_costume.dds")
		RedirectTexture("esoui/art/characterwindow/gearslot_neck.dds", "esoui/art/characterwindow/gearslot_neck.dds")
		RedirectTexture("esoui/art/characterwindow/gearslot_ring.dds", "esoui/art/characterwindow/gearslot_ring.dds")
		RedirectTexture("esoui/art/characterwindow/gearslot_mainhand.dds", "esoui/art/characterwindow/gearslot_mainhand.dds")
		RedirectTexture("esoui/art/characterwindow/gearslot_offhand.dds", "esoui/art/characterwindow/gearslot_offhand.dds")
		RedirectTexture("esoui/art/characterwindow/silhouette_human_male.dds", "esoui/art/characterwindow/silhouette_human_male.dds")
		RedirectTexture("esoui/art/characterwindow/silhouette_human_female.dds", "esoui/art/characterwindow/silhouette_human_female.dds")
		RedirectTexture("esoui/art/characterwindow/silhouette_argonian_male.dds", "esoui/art/characterwindow/silhouette_argonian_male.dds")
		RedirectTexture("esoui/art/characterwindow/silhouette_argonian_female.dds", "esoui/art/characterwindow/silhouette_argonian_female.dds")
		RedirectTexture("esoui/art/characterwindow/silhouette_khajiit_male.dds", "esoui/art/characterwindow/silhouette_khajiit_male.dds")
		RedirectTexture("esoui/art/characterwindow/silhouette_khajiit_female.dds", "esoui/art/characterwindow/silhouette_khajiit_female.dds")
		RedirectTexture("SkyrimStyleUI/media/details/inv_tab.dds", "SkyrimStyleUI/media/interface/ob_ui_blank.dds")
		RedirectTexture("SkyrimStyleUI/media/details/inv_tab3.dds", "SkyrimStyleUI/media/interface/ob_ui_blank.dds")
		RedirectTexture("SkyrimStyleUI/media/details/journal.dds", "SkyrimStyleUI/media/interface/ob_ui_blank.dds")
		RedirectTexture("SkyrimStyleUI/media/details/map.dds", "SkyrimStyleUI/media/interface/ob_ui_blank.dds")
		RedirectTexture("SkyrimStyleUI/media/details/skills.dds", "SkyrimStyleUI/media/interface/ob_ui_blank.dds")
	
  		---- Gamepad Interface ----		

		RedirectTexture("esoui/art/windows/gamepad/panelbg_focus_512.dds", "esoui/art/windows/gamepad/panelbg_focus_512.dds")
		RedirectTexture("esoui/art/windows/gamepad/gp_fullvertdiv.dds", "esoui/art/windows/gamepad/gp_fullvertdiv.dds")
		RedirectTexture("esoui/art/windows/gamepad/gp_hintbar.dds", "esoui/art/windows/gamepad/gp_hintbar.dds")
		RedirectTexture("esoui/art/windows/gamepad/gp_windowpointer.dds", "esoui/art/windows/gamepad/gp_windowpointer.dds")
		RedirectTexture("esoui/art/hud/gamepad/gp_radialmenu_thumb.dds", "esoui/art/hud/gamepad/gp_radialmenu_thumb.dds")
		RedirectTexture("esoui/art/hud/gamepad/gp_radialmenu_track.dds", "esoui/art/hud/gamepad/gp_radialmenu_track.dds")
		RedirectTexture("esoui/art/compass/gamepad/gp_area2frameanim_centers.dds", "esoui/art/compass/gamepad/gp_area2frameanim_centers.dds")
		RedirectTexture("esoui/art/compass/gamepad/gp_area2frameanim_standard_center.dds", "/esoui/art/compass/gamepad/gp_area2frameanim_standard_center.dds")
		RedirectTexture("esoui/art/compass/gamepad/gp_area2frameanim_standard_endcap.dds", "/esoui/art/compass/gamepad/gp_area2frameanim_standard_endcap.dds")

		---- Gamepad Buttons ----

		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_a.dds", "esoui/art/buttons/gamepad/xbox/nav_xbone_a.dds")
		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_b.dds", "esoui/art/buttons/gamepad/xbox/nav_xbone_b.dds")
		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_x.dds", "esoui/art/buttons/gamepad/xbox/nav_xbone_x.dds")
		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_y.dds", "SkyrimStyleUI/media/gamepad/y.dds")
		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_a_hold.dds", "esoui/art/buttons/gamepad/xbox/nav_xbone_a_hold.dds")
		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_b_hold.dds", "esoui/art/buttons/gamepad/xbox/nav_xbone_b_hold.dds")
		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_x_hold.dds", "esoui/art/buttons/gamepad/xbox/nav_xbone_x_hold.dds")
		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_y_hold.dds", "esoui/art/buttons/gamepad/xbox/nav_xbone_y_hold.dds")
		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_lb.dds", "esoui/art/buttons/gamepad/xbox/nav_xbone_lb.dds")
		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_lt.dds", "esoui/art/buttons/gamepad/xbox/nav_xbone_lt.dds")
		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_rb.dds", "esoui/art/buttons/gamepad/xbox/nav_xbone_rb.dds")
		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_rt.dds", "esoui/art/buttons/gamepad/xbox/nav_xbone_rt.dds")

		---- Gamepad Icons ----

		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_store.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_store.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_inventory.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_inventory.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_character.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_character.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_alliancewar.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_alliancewar.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_collections.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_collections.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_groups.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_groups.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_guilds.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_guilds.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_quests.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_quests.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_mail.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_mail.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_activityfinder.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_activityfinder.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_notifications.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_notifications.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_skills.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_skills.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_multiplayer.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_multiplayer.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_champion.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_champion.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_help.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_help.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_settings.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_settings.dds")
		RedirectTexture("esoui/art/menubar/gamepad/gp_playermenu_icon_logout.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_logout.dds")


	
		end

function ssiSkyrim()

		------- Gamepad Interface -------

		RedirectTexture("/SkyrimStyleUI/media/compass.dds", "/SkyrimStyleUI/media/compass.dds")
		RedirectTexture("esoui/art/windows/gamepad/panelbg_focus_512.dds", "/SkyrimStyleUI/media/background.dds")
		RedirectTexture("esoui/art/windows/gamepad/gp_fullvertdiv.dds", "/SkyrimStyleUI/media/border.dds")
		RedirectTexture("esoui/art/windows/gamepad/gp_hintbar.dds", "/SkyrimStyleUI/media/hintbar.dds")
		RedirectTexture("esoui/art/windows/gamepad/gp_windowpointer.dds", "/SkyrimStyleUI/media/windowpointer.dds")
		RedirectTexture("esoui/art/compass/gamepad/gp_compass.dds", "/SkyrimStyleUI/media/compass_gp.dds")
		RedirectTexture("esoui/art/windows/gamepad/gp_nav1_hordividerflat.dds", "/SkyrimStyleUI/media/dividerflat.dds")
		RedirectTexture("esoui/art/compass/gamepad/gp_area2frameanim_centers.dds", "/SkyrimStyleUI/media/compass_gp_glow.dds")
		RedirectTexture("esoui/art/compass/gamepad/gp_area2frameanim_standard_center.dds", "/SkyrimStyleUI/media/compass_gp_glow.dds")
		RedirectTexture("esoui/art/compass/gamepad/gp_area2frameanim_standard_endcap.dds", "/SkyrimStyleUI/media/compass_gp_edge.dds")
		RedirectTexture("esoui/art/compass/gamepad/gp_areapin2frame_ends.dds", "/SkyrimStyleUI/media/compass_gp_edge.dds")

		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_a.dds", "/SkyrimStyleUI/media/a.dds")
		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_b.dds", "/SkyrimStyleUI/media/b.dds")
		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_x.dds", "/SkyrimStyleUI/media/x.dds")
		RedirectTexture("esoui/art/buttons/gamepad/xbox/nav_xbone_y.dds", "/SkyrimStyleUI/media/y.dds")

		------- Keyboard Interface -------

		RedirectTexture("esoui/art/crafting/provisioner_indexicon_furnishings_up.dds", "esoui/art/crafting/gamepad/gp_crafting_menuicon_furnishings.dds")
		RedirectTexture("esoui/art/crafting/provisioner_indexicon_furnishings_down.dds", "esoui/art/crafting/gamepad/gp_crafting_menuicon_furnishings.dds")
		RedirectTexture("/SkyrimStyleUI/media/compass_left.dds", "/SkyrimStyleUI/media/compass_left.dds")
		RedirectTexture("/SkyrimStyleUI/media/compass_right.dds", "/SkyrimStyleUI/media/compass_right.dds")
		RedirectTexture("/esoui/art/miscellaneous/centerscreen_left.dds", "/SkyrimStyleUI/media/pc_background.dds")
		RedirectTexture("/esoui/art/miscellaneous/centerscreen_right.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/compass/compass.dds", "/SkyrimStyleUI/media/compass_c.dds")
		RedirectTexture("/esoui/art/miscellaneous/bottom_bar.dds", "/SkyrimStyleUI/media/pc_bottombar.dds")
		RedirectTexture("/esoui/art/miscellaneous/top_bar.dds", "/SkyrimStyleUI/media/pc_topbar.dds")
		RedirectTexture("/esoui/art/tooltips/munge_overlay.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("esoui/art/miscellaneous/horizontaldivider.dds", "/SkyrimStyleUI/media/border_hor.dds")
		RedirectTexture("esoui/art/characterwindow/characterwindow_leftside_divider.dds", "/SkyrimStyleUI/media/border_hor_2.dds")
		RedirectTexture("esoui/art/miscellaneous/centerscreen_topdivider.dds", "/SkyrimStyleUI/media/border_hor.dds")
		RedirectTexture("esoui/art/charactercreate/windowdivider.dds", "/SkyrimStyleUI/media/border_hor.dds")
		RedirectTexture("esoui/art/miscellaneous/wide_divider_left.dds", "/SkyrimStyleUI/media/border_hor.dds")
		RedirectTexture("esoui/art/miscellaneous/wide_divider_right.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/compass/area2frameanim_assisted_endcap.dds", "/SkyrimStyleUI/media/compass_edge.dds")
		RedirectTexture("/esoui/art/compass/area2frameanim_standard_endcap.dds", "/SkyrimStyleUI/media/compass_edge.dds")
		RedirectTexture("/esoui/art/compass/areapin2frame_ends.dds", "/SkyrimStyleUI/media/compass_edge.dds")
		RedirectTexture("/esoui/art/compass/area2frameanim_assisted_center.dds", "/SkyrimStyleUI/media/compass_glow.dds")
		RedirectTexture("/esoui/art/compass/area2frameanim_standard_center.dds", "/SkyrimStyleUI/media/compass_glow.dds")
		RedirectTexture("/esoui/art/compass/area2frameanim_centers.dds", "/SkyrimStyleUI/media/compass_glow.dds")
		RedirectTexture("/esoui/art/tooltips/ui-border.dds", "/SkyrimStyleUI/media/tooltip.dds")
		RedirectTexture("/esoui/art/tooltips/ui-border-red.dds", "/SkyrimStyleUI/media/tooltip_2.dds")
		RedirectTexture("esoui/art/miscellaneous/progressbar_frame.dds", "esoui/art/miscellaneous/gamepad/progressbar_frame.dds")
		RedirectTexture("esoui/art/unitattributevisualizer/attributebar_dynamic_frame.dds", "esoui/art/unitattributevisualizer/gamepad/gp_attributebar_dynamic_frame.dds")
		RedirectTexture("esoui/art/actionbar/abilityframe64_down.dds", "esoui/art/actionbar/gamepad/gp_abilityframe64.dds")
		RedirectTexture("esoui/art/actionbar/abilityframe64_up.dds", "esoui/art/actionbar/gamepad/gp_abilityframe64.dds")
		RedirectTexture("esoui/art/miscellaneous/centerscreen_indexarea_left.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("esoui/art/miscellaneous/centerscreen_indexarea_right.dds", "/SkyrimStyleUI/media/blank.dds")	

		------- Keyboard Icons -------

		RedirectTexture("/esoui/art/mainmenu/menubar_inventory_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_inventory.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_inventory_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_inventory.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_character_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_character.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_character_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_character.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_ava_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_alliancewar.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_ava_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_alliancewar.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_collections_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_collections.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_collections_down.dds", "/esoui/art/menubar/gamepad/gp_playermenu_icon_collections.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_group_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_groups.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_group_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_groups.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_guilds_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_guilds.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_guilds_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_guilds.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_journal_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_quests.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_journal_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_quests.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_mail_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_mail.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_mail_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_mail.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_map_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_terms.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_map_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_terms.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_market_up.dds", "/SkyrimStyleUI/media/crown.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_market_down.dds", "/SkyrimStyleUI/media/crown.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_crowncrates_up.dds", "/SkyrimStyleUI/media/crate.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_crowncrates_down.dds", "/SkyrimStyleUI/media/crate.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_notifications_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_notifications.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_notifications_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_notifications.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_skills_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_skills.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_skills_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_skills.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_social_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_multiplayer.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_social_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_multiplayer.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_champion_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_champion.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_champion_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_champion.dds")
		RedirectTexture("/esoui/art/menubar/menubar_help_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_help.dds")
		RedirectTexture("/esoui/art/menubar/menubar_help_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_help.dds")
		RedirectTexture("EsoUI/Art/Crafting/jewelry_tabIcon_icon_up.dds", "EsoUI/Art/Crafting/jewelry_tabIcon_icon_up.dds")
		RedirectTexture("EsoUI/Art/Crafting/jewelry_tabIcon_down.dds", "EsoUI/Art/Crafting/jewelry_tabIcon_down.dds")


		RedirectTexture("/esoui/art/bank/bank_tabicon_gold_up.dds", "esoui/art/bank/gamepad/gp_bank_menuicon_gold_deposit.dds")
		RedirectTexture("/esoui/art/bank/bank_tabicon_gold_down.dds", "esoui/art/bank/gamepad/gp_bank_menuicon_gold_deposit.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_quickslot_up.dds", "esoui/art/inventory/gamepad/inventory_tabicon_quickslot_default.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_quickslot_down.dds", "esoui/art/inventory/gamepad/inventory_tabicon_quickslot_default.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_craftbag_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_all.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_craftbag_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_all.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_items_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_all.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_items_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_all.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_all_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_all.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_all_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_all.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_armor_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_apparel.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_armor_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_apparel.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_consumables_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_consumables.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_consumables_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_consumables.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_crafting_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_materials.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_crafting_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_materials.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_quest_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_quest.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_quest_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_quest.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_misc_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_miscellaneous.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_misc_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_miscellaneous.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_junk_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_logout.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_junk_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_logout.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_weapons_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_weapons.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_weapons_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_weapons.dds")
		RedirectTexture("/EsoUI/Art/Crafting/jewelry_tabIcon_icon_up.dds", "esoui/art/crafting/gamepad/gp_jewelry_tabicon_icon.dds")
		RedirectTexture("/EsoUI/Art/Crafting/jewelry_tabIcon_icon_down.dds", "esoui/art/crafting/gamepad/gp_jewelry_tabicon_icon.dds")

		RedirectTexture("esoui/art/inventory/inventory_currencytab_accountwide_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_apparel.dds")
		RedirectTexture("esoui/art/inventory/inventory_currencytab_accountwide_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_apparel.dds")
		RedirectTexture("esoui/art/inventory/inventory_currencytab_oncharacter_up.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_character.dds")
		RedirectTexture("esoui/art/inventory/inventory_currencytab_oncharacter_down.dds", "esoui/art/menubar/gamepad/gp_playermenu_icon_character.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_vanitypets_up.dds", "esoui/art/treeicons/gamepad/gp_store_indexicon_vanitypets.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_vanitypets_down.dds", "esoui/art/treeicons/gamepad/gp_store_indexicon_vanitypets.dds")
		RedirectTexture("esoui/art/treeicons/collection_indexicon_assistants_up.dds", "esoui/art/treeicons/gamepad/gp_collection_indexicon_assistants.dds")
		RedirectTexture("esoui/art/treeicons/collection_indexicon_assistants_down.dds", "esoui/art/treeicons/gamepad/gp_collection_indexicon_assistants.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_costumes_up.dds", "esoui/art/treeicons/gamepad/gp_store_indexicon_costumes.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_costumes_down.dds", "esoui/art/treeicons/gamepad/gp_store_indexicon_costumes.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_trophy_up.dds", "esoui/art/treeicons/gamepad/gp_store_indexicon_trophy.dds")
		RedirectTexture("esoui/art/treeicons/store_indexicon_trophy_down.dds", "esoui/art/treeicons/gamepad/gp_store_indexicon_trophy.dds")



		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_alchemy_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_alchemy.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_blacksmithing_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_blacksmithing.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_clothing_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_clothing.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_enchanting_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_enchanting.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_fishing_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_fishing.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_itemtrait_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_itemtrait.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_provisioning_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_provisioning.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_stylematerial_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_stylematerial.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_woodworking_up.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_woodworking.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_jewelrycrafting_up.dds", "esoui/art/inventory/gamepad/gp_inventory_tabicon_craftbag_jewelrycrafting.dds")

		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_jewelrycrafting_down.dds", "esoui/art/inventory/gamepad/gp_inventory_tabicon_craftbag_jewelrycrafting.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_alchemy_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_alchemy.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_blacksmithing_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_blacksmithing.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_clothing_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_clothing.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_enchanting_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_enchanting.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_fishing_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_fishing.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_itemtrait_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_itemtrait.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_provisioning_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_provisioning.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_stylematerial_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_stylematerial.dds")
		RedirectTexture("esoui/art/inventory/inventory_tabicon_craftbag_woodworking_down.dds", "esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_woodworking.dds")

		RedirectTexture("/esoui/art/mainmenu/menubar_crowncrates_disabled.dds", "/SkyrimStyleUI/media/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_crowncrates_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_craftbag_over.dds", "SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_items_over.dds", "SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/bank/bank_tabicon_gold_over.dds", "SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_inventory_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_inventory_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_character_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_character_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_ava_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_ava_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_collections_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_collections_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_group_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_group_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_guilds_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_guilds_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_journal_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_journal_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_mail_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_mail_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_map_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_map_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_market_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_market_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_notifications_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_notifications_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_skills_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_skills_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_social_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_social_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_champion_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/mainmenu/menubar_champion_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/menubar/menubar_help_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/menubar/menubar_help_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_all_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_all_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_armor_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_armor_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_consumables_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_consumables_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_crafting_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_crafting_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_quest_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_quest_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_misc_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_misc_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_junk_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_junk_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_weapons_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_weapons_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_junk_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_junk_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_weapons_disabled.dds", "esoui/art/miscellaneous/gamepad/gp_icon_locked32.dds")
		RedirectTexture("/esoui/art/inventory/inventory_tabicon_weapons_over.dds", "/SkyrimStyleUI/media/blank.dds")
		RedirectTexture("EsoUI/Art/Inventory/inventory_tabIcon_jewelry_disabled.dds", "EsoUI/Art/Inventory/inventory_tabIcon_jewelry_disabled.dds")
		RedirectTexture("EsoUI/Art/Crafting/jewelry_tabIcon_icon_over.dds", "EsoUI/Art/Crafting/jewelry_tabIcon_icon_over.dds")


	

	end
	
function OnAddOnLoaded(eventCode, addOnName)
    if addOnName ~= ssi.appName then return end
	
	local defaults = {
		Icon = "Skyrim Style UI"
	}

    ssi.SV = ZO_SavedVars:NewAccountWide("SkyrimStyleUI_SavedVariables", ADDON_VERSION, defaults, nil)
	
	if ssi.SV.Icon == "Vanilla UI" then
		ssivanilla()
	elseif ssi.SV.Icon == "Skyrim Style UI" then
		ssiSkyrim()
	end
	
	ssi:initLAM()
	
end
  
EVENT_MANAGER:RegisterForEvent(ssi.appName, EVENT_ADD_ON_LOADED, OnAddOnLoaded)