ZO_CreateStringId("SI_BINDING_NAME_FCMQT_TOOGLE_HIDDEN", "Show/Hide FCMQT")
ZO_CreateStringId("SI_BINDING_NAME_FCMQT_TOGGLE_LOCK", "Toggle Tracker Lock On/Off")
ZO_CreateStringId("SI_BINDING_NAME_FCMQT_RESET_POS", "Reset Tracker Position")
ZO_CreateStringId("SI_BINDING_NAME_FCMQT_TOGGLE_ZONES", "Toggle Zones On/Off")
ZO_CreateStringId("SI_BINDING_NAME_FCMQT_TOGGLE_HYBRID", "Toggle Category/Zones View")
ZO_CreateStringId("SI_BINDING_NAME_FCMQT_TOGGLE_AUTO_HIDE_ZONES", "Toggle Auto Hide Zones")
ZO_CreateStringId("SI_BINDING_NAME_FCMQT_TOGGLE_HIDE_OBJ_EXCEPT_FOCUSED", "Toggle Objectives/Hints")
ZO_CreateStringId("SI_BINDING_NAME_FCMQT_TOGGLE_NO_FOCUS_TRANS", "Toggle Focused Transparency ")
ZO_CreateStringId("SI_BINDING_NAME_FCMQT_TOGGLE_FOCUS_ZONE_TRANS", "Toggle Focused Zone Transparency")
ZO_CreateStringId("SI_BINDING_NAME_FCMQT_TOGGLE_HINTS", "Toggle Hints/Hidden Items ")
