  -------------------------------------------------------
  -- Idle Animations - Main File
  -- Stratejacket (Tierney11290) & @senorblackbean - 2017 & @FischyJones (FranklyBatman) 2020
  -------------------------------------------------------


--Example for those wishing to alter:
-- emotes = {
--   ProfileName = {   -- Don't use spaces in the profile name.
--     Emote = { "/emote1", 4000, "/emote2", 7000, "/emote3" },  -- Doesn't matter what EmoteSet is called, just needs to be unique to the ProfileName.  This does "/emote1" first, then 4000 milliseconds later does "/emote2", then 3000 milliseconds after that (7000 from start), "/emote3" is performed.
--     },

emotes = {

  Adventurer = {
	PonderMap = { "/pondermap" },
	Crouch = { "/crouch" },
	Shiver = { "/shiver" },
    Relaxed = { "/idle3" },
	Confident = { "/idle5" },
    Search = { "/search" },
    Preen = { "/preen" },
    Stomp = { "/stomp" },
    Lookup = { "/lookup" },
	ScoutAhead = { "/tracker" },
    WipeForehead = { "/phew" },
  },
  
  Athlete = {
    Pushups = { "/pushups" },
    JumpingJacks = { "/jumpingjacks" },
    CrackKnuckles = { "/knuckles" },
    Situps = { "situps" },
	Stretch = { "/stretch" },
    Breathless = { "/breathless" },
	Confident = { "/idle5" },
  },
  
  Bard = {
    Drum = { "/drum" },
    Flute = { "/flute" },
    Lute = { "/lute" },
	Confident = { "/idle5" },
  },
  
  Beggar = {
    Beg = { "/beg" },
    KneelandBeg = { "/beggar" },
    BeckonandBeg = { "/beckon", 4000, "/beg" },
    ShiverandBeg = { "/cold", 4000, "/beg" },
    Shiver = { "/cold", },
    BeckonandKneelandBeg = { "/overhere", 4000, "/beckon", 8000, "/payme" , 10600, "/beg"},
    Sick = { "/sick" },
    Humble = { "/humble" },
  },
  
  Crazy = {
    FourWaves = { "/hail", 3400, "/hello", 6800, "/hail", 10200, "/hello" },
    FakeCry = { "/cry", 9000, "/idle", "/laugh", 12000, "/blowkiss" },
    LaughCry = { "/laugh", 3000, "/heartbroken" },
    KissySpit = { "/blowkiss", 2000, "/spit", 5000, "/laugh" },
    YouDisgustMe = { "/disgust", 3000, "/disapprove", 6000, "/goaway", 7500, "/shieldeyes", 12000, "/exasperated" },
    YouAreCrazy = { "/point", 1500, "/cuckoo", 4500, "/yes", "/bullshorn", "/happyface","/sadface" },
  },
  
Commander = {
	Search = {"/search"},
	Crouch = { "/crouch" },
	Armscrossed = { "/armscrossed" },
	RubHands = {"/rubhands"},
	Impatient = {"/handsonhips"},
	Blow = {"/horn"},
	Brushoff = {"/brushoff"},
	ComeOn = {"/comegetsome"},
	},
	
    -- Several items are commented out due to LAM2 limitations. Will add more later when issue is fixed.
  Custom = {
    Armscrossed = { "/armscrossed" },
	Angry = { "/angry" },
	Annoyed = { "/annoyed" },
    Applaud = { "/applaud" },
    Approve = { "/approve" },
    Beckon = { "/beckon" },
    Beg = { "/beg" },
    Beggar = { "/beggar" },
    Blowkiss = { "/blowkiss" },
    Boo = { "/boo" },
    SaluteChest = { "/salute" },
    SaluteArmCross = { "/salute2" },
	SaluteHandsTogether = { "/salute3" },
	--SaluteChestLoop = { "/saluteloop" },
	--SaluteArmCrossLoop = { "/saluteloop2" },
    --SaluteHandsTogetherLoop = { "/saluteloop3" },
	Laugh = { "/laugh" },
    --Thanks = { "/thank" },
    Lookup = { "/lookup" },
    Sick = { "/sick" },
    --Humble = { "/humble" },
    Breathless = { "/breathless" },
    Celebrate = { "/celebrate" },
    Overhere = { "/overhere" },
    Fistpump = { "/fistpump" },
    Bored = { "/bored" },
    --Drum = { "/drum" },
    --Flute = { "/flute" },
    --Lute = { "/lute" },
    ParadeRest = { "/idle2" },
    Relaxed = { "/idle3" },
    Intimidating = { "/idle4" },
    Confident = { "/idle5" },
    HandsonHips = { "/handsonhips" },
    Stretch = { "/stretch" },
    Search = { "/search" },
    Brushoff = { "/brushoff" },
    --Faint = { "/faint" },
    Shiver = { "/cold" },
    HeadScratch = { "/scratch" },
    Preen = { "/preen" },
    Sigh = { "/sigh" },
    Facepalm = { "/facepalm" },
    Crouch = { "/crouch" },
    --Provision = { "/prov" },
    --Stomp = { "/stomp" },
	DanceAltmer = { "/dancealtmer" },
    DanceArgonian = { "/danceargonian" },
    DanceBreton = { "/dancebreton" },
    DanceBosmer = { "/dancebosmer" },
    DanceDunmer = { "/dancedunmer" },
    DanceImperial = { "/danceimperial" },
    DanceKhajiit = { "/dancekhajiit" },
    DanceNord = { "/dancenord" },
    DanceOrc = { "/danceorc" },
    DanceRedguard = { "/danceredguard" },
    DrinkFromPint = { "/drink" },
    DrinkFromBottle = { "/drink3" },
    DrinkFromGlass = { "/drink2" },
    EatChicken = { "/eat" },
    EatBread = { "/eat2" },
    EatApple = { "/eat3" },
    EatPie = { "/pie" },
    EatSoup = { "/soupbowl" },
    EatMeal = { "/meal" },
    --EatSmallBread = { "/smallbread" },
    Attention = { "/attention" },
    HandtoHeart = { "/handtoheart" },
    Pray = { "/pray" },
    KneelandPray = { "/kneelpray" },
    --Wagfinger = { "/wagfinger" },
    Plead = { "/plead" },
	Shrug = { "/shrug" },
	Surprised = {"/surprised" },
    Read = { "/read" },
	Bless = { "/bless" },
	--Wand = { "/wand" },
    BlessLoop = { "/blessing" },
    JuggleFlame = { "/juggleflame" },
    Pushups = { "/pushups" },
    JumpingJacks = { "/jumpingjacks" },
    CrackKnuckles = { "/knuckles" },
    Situps = { "situps" },
    WipeForehead = { "/phew" },
    Rubhands = { "/rubhands" },
	Exasperated = { "/exasperated" },
  },

  Dancer = {
    Altmer = { "/dancealtmer" },
    Argonian = { "/danceargonian" },
    Breton = { "/dancebreton" },
    Bosmer = { "/dancebosmer" },
    Dunmer = { "/dancedunmer" },
    Imperial = { "/danceimperial" },
    Khajiit = { "/dancekhajiit" },
    Nord = { "/dancenord" },
    Orc = { "/danceorc" },
    Redguard = { "/danceredguard" },
  },
  
  Drunk = {
    DrinkFromPint = { "/drink" },
    DrinkFromBottle = { "/drink3" },
    DrinkFromPintDrunk = { "/drink", 10000, "/drunk" },
    DrinkFromBottleDrunk = { "/drink3", 10000, "/drunk" },
    DrunkDrinkFromPint = { "/drunk", 10000, "/drink" },
    DrunkDrinkfromBottle = { "/drunk", 10000, "/drink3" },
    DrinkFromPintCheer = { "/drink", 6000, "/laugh", 10000, "/cheer", 15000, "/drunk"  },
    DrinkFromBottleCheer = { "/drink3", 6000, "/laugh", 10000, "/cheer", 15000, "/drunk" },
    DanceDrunk = { "/dancedrunk", 10000, "/drink" },
    LaughDrink = { "/laugh", 3000, "/drink" },
    CheerDrunk = { "/cheer", 3000, "/fistpump", 5000, "/drunk" },
    Faint = { "/drink3", 4000, "/faint" },
  },
  
  DrunkClassy = {
    DrinkFromGlass = { "/drink2" },
    DrinkFromGlassDrunk = { "/drink2", 10000, "/drunk" },
    DrinkFromGlassCheer = { "/drink2", 6000, "/laugh", 10000, "/cheer", 15000, "/drunk" },
    LaughDrinkFromGlass = { "/laugh", 3000, "/drink2" },
    CheerDrunk = { "/fistpump", 500, "/cheer", 4000, "/drink2" },
    GratsDrinkFromGlass = { "/grats", 10000, "/drink2" },
  },
  
  Duchess = {
    Idle2 = { "/idle2" },
    Idle3 = { "/idle3" },
    Flirt = { "/flirt" },
    Tilt = { "/tilt" },
	Preen = { "/preen" },
	HandsonHips = { "/handsonhips" },
    Impatient = { "/tap", 5000, "/exasperated" },
    BrushDustoff = { "/brushoff", 4000, "/dustoff" },
    WipeForehead = { "/phew" },
    Rubhands = { "/rubhands" },
    Facepalm = { "/facepalm" },
  },
  
  Glutton = {
    EatChicken = { "/eat" },
    EatBread = { "/eat2" },
    EatApple = { "/eat3" },
    EatPie = { "/pie" },
    EatSoup = { "/soupbowl" },
    EatMeal = { "/meal" },
    EatSmallbread = { "/smallbread" },
  },
  
  Heroic = {
    Attention = { "/attention" },
    HandtoHeart = { "/handtoheart" },
    SaluteChest = { "/salute" },
    SaluteArmCross = { "/salute2" },
    SaluteHandsTogether = { "/saluteloop3" },
    Armscrossed = { "/armscrossed" },
    ParadeRest = { "/idle2" },
    Relaxed = { "/idle3" },
    Intimidating = { "/idle4" },
    Confident = { "/idle5" },
    HandsonHips = { "/handsonhips" },
    Stretch = { "/stretch" },
    Search = { "/search" },
    Brushoff = { "/brushoff" },
    HeadScratch = { "/scratch" },
    CrackKnuckles = { "/knuckles" },
    Preen = { "/preen" },
    Sigh = { "/sigh" },
    Impatient = { "/tap", 5000, "/exasperated" },
    BrushDustoff = { "/brushoff", 4000, "/dustoff" },
    WipeForehead = { "/phew" },
    Rubhands = { "/rubhands" },
    Facepalm = { "/facepalm" },
    Crouch = { "/crouch" },
	Greet = { "/greet" },
	Drink = { "/drink" },
	Rude = { "/rude" },
	TrackDown = {"/tracker"},
	ComeOn = {"/comegetsome"},
  },

  Jester = {
    ParadeRest = { "/idle2" },
    Relaxed = { "/idle3" },
	Idle4 = { "/idle4" },
    Confident = { "/idle5" },
    LeanSide = { "/leanside" },
    Bow = { "/bow" },
	Spit = { "/spit" },
	JugglePumpkins = {"jugglepumpkin"},
	Handpuppet = {"/handpuppet"},
  },

  Mage = {
    Read = { "/read" },
    JuggleFlame = { "/juggleflame" },
    JuggleFlameWrite = { "/juggleflame", 5000, "/write" },
    Wand = { "/wand", 2000, "/confused" },
    Wand2 = { "/wand", 2000, "/write" },
    RecordFindings = { "/confused", 6000, "/write" },
    Armscrossed = { "/armscrossed" },
    ParadeRest = { "/idle2" },
    Relaxed = { "/idle3" },
    Confident = { "/idle5" },
    Stretch = { "/stretch" },
    Search = { "/search" },
    Brushoff = { "/brushoff" },
    HeadScratch = { "/scratch" },
    Preen = { "/preen" },
    BrushDustoff = { "/brushoff", 4000, "/dustoff" },
    WipeForehead = { "/phew" },
    Rubhands = { "/rubhands" },
    },
	
  Normal = {
    Armscrossed = { "/armscrossed" },
    Bored = { "/bored" },
    ParadeRest = { "/idle2" },
    Relaxed = { "/idle3" },
    Intimidating = { "/idle4" },
    Confident = { "/idle5" },
    HandsonHips = { "/handsonhips" },
    Stretch = { "/stretch" },
    Search = { "/search" },
    Brushoff = { "/brushoff" },
    Shiver = { "/cold" },
    HeadScratch = { "/scratch" },
    CrackKnuckles = { "/knuckles" },
    Preen = { "/preen" },
    Sigh = { "/sigh" },
    Impatient = { "/tap", 5000, "/exasperated" },
    Shock = { "/surprised", 4000, "/huh" },
    BrushDustoff = { "/brushoff", 4000, "/dustoff" },
    WipeForehead = { "/phew" },
    Rubhands = { "/rubhands" },
    Lookup = { "/pointu", 3000, "/lookup" },
    Facepalm = { "/facepalm" },
    Crouch = { "/crouch" },
    Provision = { "/prov" },
    Stomp = { "/stomp" },
  },
  
  Religious = {
    Pray = { "/pray" },
    Kneelpray = { "/kneelpray" },
    YallneedRNGsus = { "/point", 3000, "/pointu", 6000, "/approve" },
    Wagfinger = { "/wagfinger" },
    Plead = { "/plead" },
    Read = { "/read" },
    Bless = { "/bless", 4000, "/pray" },
    BlessLoop = { "/blessing" },
    ParadeRest = { "/idle2" },
    Relaxed = { "/idle3" },
    Intimidating = { "/idle4" },
    Confident = { "/idle5" },
    HandsonHips = { "/handsonhips" },
    HeadScratch = { "/scratch" },
    CrackKnuckles = { "/knuckles" },
    Preen = { "/preen" },
    Sigh = { "/sigh" },
    Shock = { "/surprised", 4000, "/shrug" },
    BrushDustoff = { "/brushoff", 4000, "/dustoff" },
    WipeForehead = { "/phew" },
    Rubhands = { "/rubhands" },
    Lookup = { "/pointu", 3000, "/lookup" },
    Facepalm = { "/facepalm" },
    Crouch = { "/crouch" },
  },

  Scholar = {
    Threaten = { "/threaten" },
	Annoyed = { "/annoyed" },
	Tilt = { "/tilt" },
	Kneel = { "/kneel" },
	Yes = { "/yes" },
  },
  
  Telvanni = {
    Read = { "/read" },
    JuggleFlame = { "/juggleflame" },
    Armscrossed = { "/armscrossed" },
    ParadeRest = { "/idle2" },
    Relaxed = { "/idle3" },
	Plotting = { "/idle4" },
    Confident = { "/idle5" },
    Stretch = { "/stretch" },
    Preen = { "/preen" },
    BrushDustoff = { "/brushoff", 4000, "/dustoff" },
    Rubhands = { "/rubhands" },
	Thulsa = { "/doom" },
	Write = { "/write" },
	Ritual = { "/ritual" },
	TalkwithaSkull ={"/skullponder"},
	DrinkfromSkull = {"/drinkfromskull"},
  },

  Tough = {
    Threaten = { "/threaten" },
    Armscrossed = { "/armscrossed" },
    CrackKnuckles = { "/knuckles" },
    AngryKnuckles = { "/angry", 4000, "/knuckles" },
    Pushups = { "/pushups", 5000, "/stretch" },
    JumpingJacks = { "/jumpingjacks", 5000, "/stretch" },
    KnucklesStretch = { "/knuckles", 7000, "/stretch" },
    Situps = { "situps" },
    StretchYawn = { "/stretch", 7000, "/yawn" },
    Bored = { "/bored" },
    ParadeRest = { "/idle2" },
    Relaxed = { "/idle3" },
    Intimidating = { "/idle4" },
    Confident = { "/idle5" },
    Stretch = { "/stretch" },
    Search = { "/search" },
    Brushoff = { "/brushoff" },
    HeadScratch = { "/scratch" },
    CrackKnuckles = { "/knuckles" },
    Sigh = { "/sigh" },
    Impatient = { "/tap" },
    Shock = { "/surprised", 4000, "/shrug" },
    BrushDustoff = { "/brushoff", 4000, "/dustoff" },
    WipeForehead = { "/phew" },
    Rubhands = { "/rubhands" },
    Facepalm = { "/facepalm" },
    Crouch = { "/crouch" },
	TrackDown = {"/tracker"},
  },
  
Thief = {
	Lookout = {"/idle2"},
	Prepare = {"/idle3"},
	RubHands = {"/rubhands"},
	Search = {"/search"},
	Crouch = { "/crouch" },
	Threaten = { "/threaten" },
    Armscrossed = { "/armscrossed" },
	Sigh = { "/sigh" },
	CrackKnuckles = { "/knuckles" },
    Impatient = { "/tap" },
	TrackDown = {"/tracker"},
	GoQuietly = {"//goquietly"},
	},
	
TreasureHunter = {
	Lookout = {"/idle2"},
	Prepare = {"/idle3"},
	RubHands = {"/rubhands"},
	Search = {"/search"},
	Crouch = { "/crouch" },
    Armscrossed = { "/armscrossed" },
	TrackDown = {"/tracker"},
	GoQuietly = {"/goquietly"},
	Take = {"/take"},
	Phew = {"/phew"},
	Read = {"/read"},
	Map = {"/pondermap"},
	Twiddle ={"/twiddle"},
	},
	
  
  Zombie = {
    OMMNOMM = { "/eat3" },
	ARRRR = { "/idle2" },
	HRUUR = { "/idle3" },
	RAWR = { "/greet" },
	HNNGNNRR = { "/idle4" },
  },
  
    Vampire = {
    Lookout = {"/crouch"},
	Prepare = {"/idle3"},
	RubHands = {"/rubhands"},
	Search = {"/search"},
	Crouch = { "/crouch" },
    Armscrossed = { "/armscrossed" },
	TrackDown = {"/tracker"},
	GoQuietly = {"/goquietly"},
	Take = {"/take"},
	Phew = {"/phew"},
	Read = {"/read"},
	Map = {"/pondermap"},
	Twiddle ={"/twiddle"},
	Batman ={"/summonbat"},
	TalkwithaSkull ={"/skullponder"},
	DrinkfromSkull = {"/drinkfromskull"},
  },
}
