local AddonName="MapPinsTextureFix"

local function OnLoad(eventCode,addonName)
	if addonName~=AddonName then return end
	EVENT_MANAGER:UnregisterForEvent(AddonName,EVENT_ADD_ON_LOADED)
	RedirectTexture("/MapPins/textures/Chest_1.dds", "/"..AddonName.."/Chest_1.dds")
	RedirectTexture("/MapPins/textures/Chest_2.dds", "/"..AddonName.."/Chest_2.dds")
	RedirectTexture("/MapPins/textures/Lorebook_1.dds", "/"..AddonName.."/Lorebook_1.dds")
	RedirectTexture("/MapPins/textures/Lorebook_1-2.dds", "/"..AddonName.."/Lorebook_1-2.dds")
	RedirectTexture("/MapPins/textures/Lorebook_2.dds", "/"..AddonName.."/Lorebook_2.dds")
	RedirectTexture("/MapPins/textures/Lorebook_2-2.dds", "/"..AddonName.."/Lorebook_2-2.dds")
	RedirectTexture("/MapPins/textures/Scroll_1.dds", "/"..AddonName.."/Scroll_1.dds")
	RedirectTexture("/MapPins/textures/Skyshard_1.dds", "/"..AddonName.."/Skyshard_1.dds")
	RedirectTexture("/MapPins/textures/Treasure_1.dds", "/"..AddonName.."/Treasure_1.dds")
	RedirectTexture("/MapPins/textures/Treasure_1-2.dds", "/"..AddonName.."/Treasure_1-2.dds")
	RedirectTexture("/MapPins/textures/Treasure_2.dds", "/"..AddonName.."/Treasure_2.dds")
	RedirectTexture("/MapPins/textures/Treasure_3.dds", "/"..AddonName.."/Treasure_3.dds")
	RedirectTexture("/MapPins/textures/Treasure_4.dds", "/"..AddonName.."/Treasure_4.dds")
	RedirectTexture("/MapPins_console/textures/Chest_1.dds", "/"..AddonName.."/Chest_1.dds")
	RedirectTexture("/MapPins_console/textures/Chest_2.dds", "/"..AddonName.."/Chest_2.dds")
	RedirectTexture("/MapPins_console/textures/Lorebook_1.dds", "/"..AddonName.."/Lorebook_1.dds")
	RedirectTexture("/MapPins_console/textures/Lorebook_1-2.dds", "/"..AddonName.."/Lorebook_1-2.dds")
	RedirectTexture("/MapPins_console/textures/Lorebook_2.dds", "/"..AddonName.."/Lorebook_2.dds")
	RedirectTexture("/MapPins_console/textures/Lorebook_2-2.dds", "/"..AddonName.."/Lorebook_2-2.dds")
	RedirectTexture("/MapPins_console/textures/Scroll_1.dds", "/"..AddonName.."/Scroll_1.dds")
	RedirectTexture("/MapPins_console/textures/Skyshard_1.dds", "/"..AddonName.."/Skyshard_1.dds")
	RedirectTexture("/MapPins_console/textures/Treasure_1.dds", "/"..AddonName.."/Treasure_1.dds")
	RedirectTexture("/MapPins_console/textures/Treasure_1-2.dds", "/"..AddonName.."/Treasure_1-2.dds")
	RedirectTexture("/MapPins_console/textures/Treasure_2.dds", "/"..AddonName.."/Treasure_2.dds")
	RedirectTexture("/MapPins_console/textures/Treasure_3.dds", "/"..AddonName.."/Treasure_3.dds")
	RedirectTexture("/MapPins_console/textures/Treasure_4.dds", "/"..AddonName.."/Treasure_4.dds")
end

EVENT_MANAGER:RegisterForEvent(AddonName,EVENT_ADD_ON_LOADED,OnLoad)
