SetItemList = {
	"Hat of Adroitness",
	"Necklace of Adroitness",
	"Robe of Adroitness",
	"Sash of Adroitness",
	"Staff of Adroitness",
	"Afflicted Battle Axe",
	"Afflicted Choker",
	"Afflicted Cuirass",
	"Afflicted Gauntlets",
	"Afflicted Helm",
	"Afflicted Pauldrons",
	"Afflicted Sabatons",
	"Cuirass of Akatosh's Blessing",
	"Gauntlets of Akatosh's Blessing",
	"Greaves of Akatosh's Blessing",
	"Helm of Akatosh's Blessing",
	"Necklace of Akatosh's Blessing",
	"Pauldrons of Akatosh's Blessing",
	"Shield of Akatosh's Blessing",
	"Bastion of the Dragon",
	"Clasp of the Dragon",
	"Claw of the Dragon",
	"Crest of the Dragon",
	"Scales of the Dragon",
	"Alessia's Bulwark  (Crafted Set)",
	"Alessian Bracers",
	"Alessian Breeches",
	"Alessian Choker",
	"Alessian Cuirass",
	"Alessian Gauntlets",
	"Alessian Gloves",
	"Alessian Greaves",
	"Alessian Hat",
	"Alessian Helm",
	"Alessian Helmet",
	"Alessian Jack",
	"Alessian Leg Guards",
	"Alessian Necklace",
	"Alessian Pendant",
	"Alessian Robe",
	"Breeches of Almalexia's Mercy",
	"Epaulets of Almalexia's Mercy",
	"Gloves of Almalexia's Mercy",
	"Hat of Almalexia's Mercy",
	"Locket of Almalexia's Mercy",
	"Robe of Almalexia's Mercy",
	"Breeches of Alteration Mastery",
	"Epaulets of Alteration Mastery",
	"Gloves of Alteration Mastery",
	"Hat of Alteration Mastery",
	"Robe of Alteration Mastery",
	"Sash of Alteration Mastery",
	"Auriel's Bow",
	"Auriel's Ring",
	"Tenth Ring of Trinimac",
	"White Bow of Alinor",
	"Breeches of the Apprentice",
	"Gloves of the Apprentice",
	"Robe of the Apprentice",
	"Sash of the Apprentice",
	"Shoes of the Apprentice",
	"Breeches of the Arch-Mage",
	"Epaulets of the Arch-Mage",
	"Gloves of the Arch-Mage",
	"Hat of the Arch-Mage",
	"Pendant of the Arch-Mage",
	"Robe of the Arch-Mage",
	"Sash of the Arch-Mage",
	"Belt of the Archer's Mind",
	"Boots of the Archer's Mind",
	"Bracers of the Archer's Mind",
	"Helmet of the Archer's Mind",
	"Jack of the Archer's Mind",
	"Armor of the Seducer (Crafted)",
	"Ashen Grip (Crafted Set)",
	"Barkskin Belt",
	"Barkskin Bracers",
	"Barkskin Jack",
	"Barkskin Leg Guards",
	"Barkskin Shoulder Cops",
	"Beads of Beckoning Steel",
	"Cuirass of Beckoning Steel",
	"Gauntlets of Beckoning Steel",
	"Girdle of Beckoning Steel",
	"Greaves of Beckoning Steel",
	"Energizing Ring of the Advancing Yokeda",
	"Greatsword of the Advancing Yokeda",
	"Necklace of the Advancing Yokeda",
	"Refreshing Ring of the Advancing Yokeda",
	"Blood Spawn's Epaulets",
	"Blood Spawn's Guise",
	"Cuirass of the Brute",
	"Gauntlets of the Brute",
	"Greaves of the Brute",
	"Helm of the Brute",
	"Warhammer of the Brute",
	"Covenant's Breeches",
	"Covenant's Epaulets",
	"Covenant's Gloves",
	"Covenant's Hat",
	"Covenant's Robe",
	"Covenant's Sash",
	"Covenant's Shoes",
	"Dominion's Breeches",
	"Dominion's Epaulets",
	"Dominion's Gloves",
	"Dominion's Hat",
	"Dominion's Robe",
	"Dominion's Sash",
	"Dominion's Shoes",
	"Pact's Breeches",
	"Pact's Epaulets",
	"Pact's Gloves",
	"Pact's Hat",
	"Pact's Robe",
	"Pact's Sash",
	"Pact's Shoes",
	"Burning Spellweave Breeches",
	"Burning Spellweave Epaulets",
	"Burning Spellweave Gloves",
	"Burning Spellweave Hat",
	"Burning Spellweave Jerkin",
	"Burning Spellweave Sash",
	"Burning Spellweave Shoes",
	"Cuirass of the Construct",
	"Girdle of the Construct",
	"Greaves of the Construct",
	"Helm of the Construct",
	"Pauldrons of the Construct",
	"Boots of the Crusader",
	"Bracers of the Crusader",
	"Helmet of the Crusader",
	"Jack of the Crusader",
	"Leg Guards of the Crusader",
	"Shield of the Crusader",
	"Curse-Eating Breeches",
	"Curse-Eating Epaulets",
	"Curse-Eating Gloves",
	"Curse-Eating Hat",
	"Curse-Eating Robe",
	"Curse-Eating Shoes",
	"Curse-Eating Staff",
	"Cuirass of Cyrodiil's Crest",
	"Gauntlets of Cyrodiil's Crest",
	"Girdle of Cyrodiil's Crest",
	"Helm of Cyrodiil's Crest",
	"Locket of Cyrodiil's Crest",
	"Pauldrons of Cyrodiil's Crest",
	"Sabatons of Cyrodiil's Crest",
	"Darkstride Belt",
	"Darkstride Boots",
	"Darkstride Bracers",
	"Darkstride Helmet",
	"Darkstride Jack",
	"Covenant's Greatsword",
	"Covenant's Signet",
	"Dominion's Greatsword",
	"Dominion's Signet",
	"Pact's Greatsword",
	"Pact's Signet",
	"Death's Wind (Crafted Set)",
	"Hammer of the Resilient Yokeda",
	"Necklace of the Resilient Yokeda",
	"Ring of the Resilient Yokeda",
	"Shield of the Resilient Yokeda",
	"Breeches of the Desert Rose",
	"Epaulets of the Desert Rose",
	"Hat of the Desert Rose",
	"Sandals of the Desert Rose",
	"Tunic of the Desert Rose",
	"Breeches of Destruction Mastery",
	"Epaulets of Destruction Mastery",
	"Gloves of Destruction Mastery",
	"Hat of Destruction Mastery",
	"Robe of Destruction Mastery",
	"Sash of Destruction Mastery",
	"Arsonist's Staff",
	"Hromir's Ice Staff",
	"Hromir's Ring",
	"Levin Master's Ring",
	"Ring of Bitter Mercy",
	"Ring of Blue Ice",
	"Ring of Embers",
	"Ring of St Llothis",
	"Spear of Bitter Mercy",
	"Staff of Everfrost",
	"Staff of Fulmination",
	"Staff of St Llothis",
	"Aether Blazing Staff",
	"Aether Necklace of Undoing",
	"Aether Ring of Empowerment",
	"Aether Staff of Bitter Ice",
	"Aether Staff of Enervation",
	"Energizing Aether Ring",
	"Armor of the First Titan",
	"Battleaxe of Medrike",
	"Belt of the First Titan",
	"Boots of the First Titan",
	"Gauntlets of the First Titan",
	"Glacial Staff of Nomeg Haga",
	"Greaves of the First Titan",
	"Hammer of Anaxes",
	"Pauldrons of the First Titan",
	"Soul-Reaving Bow",
	"Staff of Zymel Hriz",
	"The Bestial Rampart",
	"Cuirass of the Dreugh King Slayer",
	"Greatsword of the Dreugh King Slayer",
	"Greaves of the Dreugh King Slayer",
	"Pauldrons of the Dreugh King Slayer",
	"Pendant of the Dreugh King Slayer",
	"Cuirass of Durok's Bane",
	"Girdle of Durok's Bane",
	"Greaves of Durok's Bane",
	"Helm of Durok's Bane",
	"Pauldrons of Durok's Bane",
	"Covenant's Band",
	"Covenant's Bow",
	"Dominion's Band",
	"Dominion's Bow",
	"Pact's Band",
	"Pact's Bow",
	"Ebon Cuirass",
	"Ebon Gauntlets",
	"Ebon Girdle",
	"Ebon Greaves",
	"Ebon Helm",
	"Ebon Pauldrons",
	"Ebon Sabatons",
	"Elegant Epaulets",
	"Elegant Gloves",
	"Elegant Hat",
	"Elegant Robe",
	"Elegant Sash",
	"Elegant Shoes",
	"Cuirass of Elf Bane",
	"Gauntlets of Elf Bane",
	"Girdle of Elf Bane",
	"Greaves of Elf Bane",
	"Helm of Elf Bane",
	"Warhammer of Elf Bane",
	"Embershield Cuirass",
	"Embershield Gauntlets",
	"Embershield Girdle",
	"Embershield Greaves",
	"Embershield Helm",
	"Embershield Pauldron",
	"Embershield Sabatons",
	"The Engine Guardian's Epaulets",
	"The Engine Guardian's Guise",
	"The Eyes of Mara (Crafted Set)",
	"Fiord's Arm Cops",
	"Fiord's Guards",
	"Fiord's Helmet",
	"Fiord's Jack",
	"Fiord's Ring",
	"Cuirass of the Footman",
	"Girdle of the Footman",
	"Greaves of the Footman",
	"Sabatons of the Footman",
	"Shield of the Footman",
	"Locket of the Footman",
	"Memento of the Footman",
	"Covenant's Loop",
	"Covenant's Restoration Staff",
	"Dominion's Loop",
	"Dominion's Restoration Staff",
	"Pact's Loop",
	"Pact's Restoration Staff",
	"Belt of the Hawk's Eye",
	"Bracers of the Hawk's Eye",
	"Cowl of the Hawk's Eye",
	"Jack of the Hawk's Eye",
	"Leg Guards of the Hawk's Eye",
	"Ring of the Hawk's Eye",
	"Shoulder Cops of the Hawk's Eye",
	"Breeches of the Healer",
	"Epaulets of the Healer",
	"Hood of the Healer",
	"Robe of the Healer",
	"Shoes of the Healer",
	"Aether Necklace of Mending",
	"Aether Ring of Mending",
	"Aether Ring of Restoration",
	"Aether Staff of Mending",
	"Covenant's Cuirass",
	"Covenant's Gauntlets",
	"Covenant's Girdle",
	"Covenant's Greaves",
	"Covenant's Helm",
	"Covenant's Pauldron",
	"Covenant's Sabatons",
	"Dominion's Cuirass",
	"Dominion's Gauntlets",
	"Dominion's Girdle",
	"Dominion's Greaves",
	"Dominion's Helm",
	"Dominion's Pauldron",
	"Dominion's Sabatons",
	"Pact's Cuirass",
	"Pact's Gauntlets",
	"Pact's Girdle",
	"Pact's Greaves",
	"Pact's Helm",
	"Pact's Pauldron",
	"Pact's Sabatons",
	"Savior's Arm Cops",
	"Savior's Belt",
	"Savior's Boots",
	"Savior's Bracers",
	"Savior's Guards",
	"Savior's Helmet",
	"Savior's Jack",
	"Hist Bark (Crafted Set)",
	"Hunding's Rage (Crafted Set)",
	"Ice Furnace Cuirass",
	"Ice Furnace Gauntlets",
	"Ice Furnace Greaves",
	"Ice Furnace Pauldrons",
	"Ice Furnace Sabatons",
	"Cuirass of the Yokeda",
	"Gauntlets of the Yokeda",
	"Girdle of the Yokeda",
	"Greaves of the Yokeda",
	"Helm of the Yokeda",
	"Pauldron of the Yokeda",
	"Sabatons of the Yokeda",
	"Amulet of Conflagration",
	"Burning Amulet",
	"Burning Brand",
	"Flamedancer",
	"Hopesfire",
	"Trueflame",
	"Cuirass of the Juggernaut",
	"Greaves of the Juggernaut",
	"Helm of the Juggernaut",
	"Pauldrons of the Juggernaut",
	"Shield of the Juggernaut",
	"Kagrenac's Hope (Crafted Set)",
	"Battle Axe of the Knightmare",
	"Cuirass of the Knightmare",
	"Gauntlets of the Knightmare",
	"Greaves of the Knightmare",
	"Helm of the Knightmare",
	"Belt of Kyne's Flight",
	"Bow of Kyne's Flight",
	"Bracers of Kyne's Flight",
	"Helmet of Kyne's Flight",
	"Jack of Kyne's Flight",
	"Leg Guards of Kyne's Flight",
	"Ring of Kyne's Flight",
	"Boots of Kyne's Kiss",
	"Bracers of Kyne's Kiss",
	"Helmet of Kyne's Kiss",
	"Jack of Kyne's Kiss",
	"Shoulder Cops of Kyne's Kiss",
	"Band of Cyrodiil's Light",
	"Breeches of Cyrodiil's Light",
	"Epaulets of Cyrodiil's Light",
	"Gloves of Cyrodiil's Light",
	"Hat of Cyrodiil's Light",
	"Ring of Cyrodiil's Light",
	"Robe of Cyrodiil's Light",
	"Lord's Cuirass",
	"Lord's Gauntlets",
	"Lord's Greaves",
	"Lord's Helm",
	"Lord's Longsword",
	"Lord's Pauldrons",
	"Lord's Shield",
	"Breeches of the Magicka Furnace",
	"Epaulets of the Magicka Furnace",
	"Hat of the Magicka Furnace",
	"Loop of the Magicka Furnace",
	"Necklace of the Magicka Furnace",
	"Ring of the Magicka Furnace",
	"Robe of the Magicka Furnace",
	"Magnus' (Crafted Set)",
	"Maw of the Infernal's Epaulets",
	"Maw of the Infernal's Hat",
	"Belt of the Morag Tong",
	"Bracers of the Morag Tong",
	"Dagger of the Morag Tong",
	"Helmet of the Morag Tong",
	"Pendant of the Morag Tong",
	"Breeches of Necropotence",
	"Epaulets of Necropotence",
	"Gloves of Necropotence",
	"Hat of Necropotence",
	"Robe of Necropotence",
	"Sash of Necropotence",
	"Shoes of Necropotence",
	"Lord-Warden Helm",
	"Lord-Warden Shoulders",
	"Nerien'eth's Epaulets",
	"Nerien'eth's Hat",
	"The Night Mother (Crafted Set)",
	"Bracers of the Night Mother",
	"Helmet of the Night Mother",
	"Jack of the Night Mother",
	"Leg Guards of the Night Mother",
	"Shoulder Cops of the Night Mother",
	"Night's Silence (Crafted Set)",
	"Bogdan the Nightflame's Epaulets",
	"Bogdan the Nightflame's Guise",
	"Nightshade Bracers",
	"Nightshade Dagger",
	"Nightshade Helmet",
	"Nightshade Jack",
	"Nightshade Leg Guards",
	"Nightshade Necklace",
	"Nightshade Shoulder Cops",
	"Cuirass of Nikulas",
	"Helm of Nikulas",
	"Pauldrons of Nikulas",
	"Sabatons of Nikulas",
	"Shield of Nikulas",
	"Breeches of the Noble Duelist",
	"Dagger of the Noble Duelist",
	"Epaulets of the Noble Duelist",
	"Harness of the Noble Duelist",
	"Shoes of the Noble Duelist",
	"Boots of Oblivion",
	"Bracers of Oblivion",
	"Helmet of Oblivion",
	"Jack of Oblivion",
	"Leg Guards of Oblivion",
	"Shoulder Cops of Oblivion",
	"Oblivion's Foe (Crafted Set)",
	"Orgnum's Scales (Crafted Set)",
	"Ophidian Bow of Venom",
	"Ophidian Necklace of Venom",
	"Ophidian Ring of Energy",
	"Ophidian Ring of Spirit",
	"Covenant's Choker",
	"Covenant's Shield",
	"Covenant's Sword",
	"Dominion's Choker",
	"Dominion's Shield",
	"Dominion's Sword",
	"Pact's Choker",
	"Pact's Shield",
	"Pact's Sword",
	"Breeches of Prayer",
	"Epaulets of Prayer",
	"Hat of Prayer",
	"Robe of Prayer",
	"Sash of Prayer",
	"Prisoner's Breeches",
	"Prisoner's Gloves",
	"Prisoner's Sash",
	"Prisoner's Shirt",
	"Prisoner's Shoes",
	"Ophidian Belt of Celerity",
	"Ophidian Boots of Celerity",
	"Ophidian Bracers of Celerity",
	"Ophidian Chausses of Celerity",
	"Ophidian Helm",
	"Ophidian Jack",
	"Ophidian Spaulders of Celerity",
	"Cuirass of Rage",
	"Gauntlets of Rage",
	"Greaves of Rage",
	"Helm of Rage",
	"Sabatons of Rage",
	"Belt of the Ranger",
	"Boots of the Ranger",
	"Bracers of the Ranger",
	"Helmet of the Ranger",
	"Jack of the Ranger",
	"Ravaging Band",
	"Ravaging Choker",
	"Ravaging Cuirass",
	"Ravaging Gauntlets",
	"Ravaging Greatsword",
	"Ravaging Greaves",
	"Ravaging Ring",
	"Belt of the Red Mountain",
	"Helmet of the Red Mountain",
	"Jack of the Red Mountain",
	"Leg Guards of the Red Mountain",
	"Shoulder Cops of the Red Mountain",
	"Healing Staff of Thorn",
	"Restoration Ring of Thorn",
	"Ring of Indarys",
	"Staff of Indarys",
	"Auriel's Shield",
	"Crusader's Mace",
	"Crusader's Necklace",
	"Elf-Doom Maul",
	"Necklace of Sardavar",
	"Shield of the Man-Bull",
	"Breeches of the Onslaught",
	"Epaulets of the Onslaught",
	"Hood of the Onslaught",
	"Robe of the Onslaught",
	"Shoes of the Onslaught",
	"Breeches of the Necromancer",
	"Epaulets of the Necromancer",
	"Gloves of the Necromancer",
	"Hood of the Necromancer",
	"Robe of the Necromancer",
	"Breeches of Sanctuary",
	"Epaulets of Sanctuary",
	"Hat of Sanctuary",
	"Loop of Sanctuary",
	"Ring of Sanctuary",
	"Robe of Sanctuary",
	"Staff of Sanctuary",
	"Belt of Salvation",
	"Boots of Salvation",
	"Bracers of Salvation",
	"Helmet of Salvation",
	"Jack of Salvation",
	"Leg Guards of Salvation",
	"Shoulder Cops of Salvation",
	"Malubeth The Scourger's Epaulets",
	"Malubeth The Scourger's Guise",
	"Boots of the Sentry",
	"Bow of the Sentry",
	"Bracers of the Sentry",
	"Helmet of the Sentry",
	"Jack of the Sentry",
	"Leg Guards of the Sentry",
	"Cuirass of the Sergeant",
	"Greaves of the Sergeant",
	"Helm of the Sergeant",
	"Pauldron of the Sergeant",
	"Sabatons of the Sergeant",
	"Breeches of the Shadow Dancer",
	"Cowl of the Shadow Dancer",
	"Gloves of the Shadow Dancer",
	"Shirt of the Shadow Dancer",
	"Shoes of the Shadow Dancer",
	"Band of the Shadow Walker",
	"Boots of the Shadow Walker",
	"Leg Guards of the Shadow Walker",
	"Pendant of the Shadow Walker",
	"Ring of the Shadow Walker",
	"Shalidor's Curse (Crafted Set)",
	"Covenant's Arm Cops",
	"Covenant's Belt",
	"Covenant's Boots",
	"Covenant's Bracers",
	"Covenant's Guards",
	"Covenant's Helmet",
	"Covenant's Jack",
	"Dominion's Arm Cops",
	"Dominion's Belt",
	"Dominion's Boots",
	"Dominion's Bracers",
	"Dominion's Guards",
	"Dominion's Helmet",
	"Dominion's Jack",
	"Pact's Arm Cops",
	"Pact's Belt",
	"Pact's Boots",
	"Pact's Bracers",
	"Pact's Guards",
	"Pact's Helmet",
	"Pact's Jack",
	"Bracers of the Lich",
	"Crown of the Lich",
	"Dylora's Staff",
	"Epaulets of the Lich",
	"Robe of the Lich",
	"Embrace of Shadows",
	"Footpads of Shadows",
	"Guards of Shadows",
	"Hands of Shadows",
	"Mask of Shadows",
	"Epaulets of the Sun",
	"Hood of the Sun",
	"Necklace of the Sun",
	"Robe of the Sun",
	"Staff of the Sun",
	"Boots of the Skirmisher",
	"Bracers of the Skirmisher",
	"Helmet of the Skirmisher",
	"Jack of the Skirmisher",
	"Leg Guards of the Skirmisher",
	"Shoulder Cops of the Skirmisher",
	"Song of Lamae (Crafted Set)",
	"Band of Soulshine",
	"Cuirass of Soulshine",
	"Greaves of Soulshine",
	"Helm of Soulshine",
	"Pauldrons of Soulshine",
	"Pendant of Soulshine",
	"Ring of Soulshine",
	"Spawn Of Mephala's Epaulets",
	"Spawn Of Mephala's Guise",
	"The Spectre's Eye (Crafted Set)",
	"Breeches of Stendarr",
	"Epaulets of Stendarr",
	"Hat of Stendarr",
	"Necklace of Stendarr",
	"Robe of Stendarr",
	"Cuirass of the Storm Knight",
	"Gauntlets of the Storm Knight",
	"Greaves of the Storm Knight",
	"Helm of the Storm Knight's Plate",
	"Pauldrons of the Storm Knight",
	"Pendant of the Storm Knight",
	"Shield of the Storm Knight",
	"Stygian Boots",
	"Stygian Guards",
	"Stygian Arm Cops",
	"Stygian Belt",
	"Stygian Bracers",
	"Stygian Dagger",
	"Stygian Helmet",
	"Stygian Jack",
	"Sunderflame Arm Cops",
	"Sunderflame Belt",
	"Sunderflame Boots",
	"Sunderflame Bracers",
	"Sunderflame Guards",
	"Sunderflame Helmet",
	"Sunderflame Jack",
	"Band of Syrabane",
	"Epaulets of Syrabane",
	"Gloves of Syrabane",
	"Ring of Syrabane",
	"Robe of Syrabane",
	"Thunderous Cuirass",
	"Thunderous Greaves",
	"Thunderous Pauldrons",
	"Thunderous Pendant",
	"Thunderous Sabatons",
	"Torug's Pact (Crafted Set)",
	"Forge Master's Ring",
	"Malacath's Ring",
	"The Ebon Sledge",
	"Volendrung",
	"Cuirass of Truth",
	"Girdle of Truth",
	"Greaves of Truth",
	"Helm of Truth",
	"Pauldrons of Truth",
	"Warhammer of Truth",
	"Necklace of the Two-Fanged Snake",
	"Ring of the Two-Fanged Snake",
	"Sword of the Two-Fanged Snake",
	"Twilight's Embrace (Crafted Set)",
	"Axe of the Elder Sister",
	"Axe of the Younger Sister",
	"Boots of the Twin Sisters",
	"Bracers of the Twin Sisters",
	"Helmet of the Twin Sisters",
	"Jack of the Twin Sisters",
	"Leg Guards of the Twin Sisters",
	"Badge of the Unassailable",
	"Band of the Unassailable",
	"Cuirass of the Unassailable",
	"Greaves of the Unassailable",
	"Helm of the Unassailable",
	"Ring of the Unassailable",
	"Shield of the Unassailable",
	"Breeches of the Undaunted Bastion",
	"Epaulets of the Undaunted Bastion",
	"Gloves of the Undaunted Bastion",
	"Hat of the Undaunted Bastion",
	"Jerkin of the Undaunted Bastion",
	"Sash of the Undaunted Bastion",
	"Shoes of the Undaunted Bastion",
	"Arm Cops of the Undaunted Infiltrator",
	"Belt of the Undaunted Infiltrator",
	"Boots of the Undaunted Infiltrator",
	"Bracers of the Undaunted Infiltrator",
	"Guards of the Undaunted Infiltrator",
	"Helmet of the Undaunted Infiltrator",
	"Jack of the Undaunted Infiltrator",
	"Breeches of the Undaunted Unweaver",
	"Epaulets of the Undaunted Unweaver",
	"Gloves of the Undaunted Unweaver",
	"Hat of the Undaunted Unweaver",
	"Jerkin of the Undaunted Unweaver",
	"Sash of the Undaunted Unweaver",
	"Shoes of the Undaunted Unweaver",
	"Valkyn Skori's Hat",
	"Valkyn Skoria's Epaulets",
	"Vampire's Kiss (Crafted Set)",
	"Covenant's Axe",
	"Covenant's Beads",
	"Dominion's Axe",
	"Dominion's Beads",
	"Pact's Axe",
	"Pact's Beads",
	"Cowl of the Warlock",
	"Epaulets of the Warlock",
	"Focus of the Warlock",
	"Robes of the Warlock",
	"Signet of the Warlock",
	"Boots of the Viper",
	"Fang of the Viper",
	"Helmet of the Viper",
	"Shoulder Cops of the Viper",
	"Throat-Scales of the Viper",
	"Belt of Cyrodiil's Ward",
	"Boots of Cyrodiil's Ward",
	"Bracers of Cyrodiil's Ward",
	"Helmet of Cyrodiil's Ward",
	"Jack of Cyrodiil's Ward",
	"Leg Guards of Cyrodiil's Ward",
	"Shoulder Cops of Cyrodiil's Ward",
	"Arm Cops of the Air",
	"Belt of the Air",
	"Boots of the Air",
	"Bracers of the Air",
	"Guards of the Air",
	"Helmet of the Air",
	"Jack of the Air",
	"Cuirass of the Fire",
	"Gauntlets of the Fire",
	"Girdle of the Fire",
	"Greaves of the Fire",
	"Helm of the Fire",
	"Pauldron of the Fire",
	"Sabatons of the Fire",
	"Breeches of Martial Knowledge",
	"Epaulets of Martial Knowledge",
	"Gloves of Martial Knowledge",
	"Hat of Martial Knowledge",
	"Sash of Martial Knowledge",
	"Shirt of Martial Knowledge",
	"Shoes of Martial Knowledge",
	"Way of the Arena (Crafted Set)",
	"Werewolf Hide Band",
	"Werewolf Hide Helmet",
	"Werewolf Hide Jack",
	"Werewolf Hide Ring",
	"Werewolf Hide Shoulder Cops",
	"Whitestrake's (Crafted Set)",
	"The Willow's Path (Crafted Set)",
	"Aether Breeches",
	"Aether Epaulets",
	"Aether Gloves",
	"Aether Hat",
	"Aether Robes",
	"Aether Sash",
	"Aether Shoes",
	"Breeches of the Worm Cult",
	"Epaulets of the Worm Cult",
	"Gloves of the Worm Cult",
	"Hat of the Worm Cult",
	"Robe of the Worm Cult",
	"Sash of the Worm Cult",
	"Shoes of the Worm Cult",
	"Covenant's Ice Staff",
	"Covenant's Inferno Staff",
	"Covenant's Lightning Staff",
	"Covenant's Ring",
	"Dominion's Ice Staff",
	"Dominion's Inferno Staff",
	"Dominion's Lightning Staff",
	"Dominion's Ring",
	"Pact's Ice Staff",
	"Pact's Inferno Staff",
	"Pact's Lightning Staff",
	"Pact's Ring",
}