FCMQT.language = {}
FCMQT.language.us = {
	-- Menu
	-- Version : 1.5.5.25
	["lang_quests_category_view_settings"] = "Settings for Category Zone View",
	["lang_class_show_zone"] = "Show zone in Class Category Zone View",
	["lang_class_show_zone_tip"] = "When using Category Zone View show the zone of the Class quests",
	["lang_craft_show_zone"] = "Show zone in Craft Category Zone View",
	["lang_craft_show_zone_tip"] = "When using Category Zone View show the zone of the Crafting quests",
	["lang_Group_show_zone"] = "Show zone in Group Category Zone View",
	["lang_Group_show_zone_tip"] = "When using Category Zone View show the zone of the Group quests",
	["lang_Dungeon_show_zone"] = "Show zone in Dungeon Category Zone View",
	["lang_Dungeon_show_zone_tip"] = "When using Category Zone View show the zone of the Dungeon quests",
	["lang_Raid_show_zone"] = "Show zone in Raid Category Zone View",
	["lang_Raid_show_zone_tip"] = "When using Category Zone View show the zone of the Raid quests",
	["lang_HideOptObjective"] = "Hide Optional Objectives",
	["lang_HideOptObjective_tip"] = "Hide quests optional objectives",
	["lang_HideOptionalInfo"] = "Hide Optional Information",
	["lang_HideOptionalInfo_tip"] = "Hide Quest Optional Information",
	["lang_HideHintsOption"] = "Hide Quest Hints",
	["lang_HideHintsOption_tip"] = "Hide hints for the quest",
	["lang_HideHiddenOptions"] = "Hide Hidden Quest Hints",
	["lang_HideHiddenOptions_tip"] = "Hide hidden quest hints.",
	["lang_HintColor"] = "Quest Hint Color",
	["lang_HintColor_tip"] = "Color for hints for quest",
	["lang_HintCompleteColor"] = "Quest Hints Completed Color",
	["lang_HintCompleteColor_tip"] = "Quest hints completed color.",
	["lang_HideInCombat"] = "Hide tracker when in combat",
	["lang_HideInCombat_tip"] = "Hide tracker when in combat",
	["lang_QuestObjIcon"] = "Show Quest Step Icons",
	["lang_QuestObjIcon_tip"] = "Show Quest Step Icons instead of text symbols.",
	["lang_HideObjOption"] = "Hide Objectives for all quests EXCEPT",
	["lang_HideObjOption_tip"] = "Option to hide all objectives except for the three options.  Disabled will ignore this option, Focused Quest would hide all objectives except focused quest, Focused Zone will hide all objectives except for the zone the focused quest is in.",
	["lang_Miscellaneous"] = "Miscellaneous",
	["lang_Toggle_AutoHide_off"] = "Auto Hide Zone/Category set to Off",
	["lang_Toggle_AutoHide_on"] = "Auto Hide Zone/Category set to On",
	["lang_Collaspe_All_Zones"] = "Collaspe All Zones/Categories",
	["lang_Expand_All_Zones"] = "Expand All Zones/Categories",
	["lang_Toggle_Category_off"] = "Change to Zone View",
	["lang_Toggle_Category_on"] = "Change to Category View",
	["lang_Toggle_NotFocusTrans_on"] = "Not Focused Transparency set to On",
	["lang_Toggle_NotFocusTrans_off"] = "Not Focused Transparency set to Off",
	["lang_Toggle_HintsHidden_on"] = "Hide Hints and Hidden Hints to On",
	["lang_Toggle_HintsHidden_off"] = "Hide Hints and Hidden Hints to  Off",
	["lang_Toggle_HideObjOption_Disabled"] = "Objectives on for All Quests",
	["lang_Toggle_HideObjOption_FocusedQuest"] = "Objectives on for Focused Quest Only",
	["lang_Toggle_HideObjOption_FocusedZone"] = "Objectives on for Focused Zone Quests",
	["lang_tmp_FCMQTMessage"] = "<<1>>: <<2>>",
	["lang_tmp_FCMQTMessage_Error"] = "ERROR <<1>>: <<2>>",
	
	
	
	
	
	
	["lang_Chat_AddonMessages"] = "Enable Chat Messages for Addon",
	["lang_Chat_AddonMessages_tip"] = "Enable chat messages, messages from addon as to changes by keybinds, errors, etc.",
	["lang_Chat_QuestInfo"] = "Enable Chat Messages for Quest Info",
	["lang_Chat_QuestInfo_tip"] = "Enable chat messages for quest information.",
	["lang_chat_settings"] = "Chat Settings",
	["lang_Chat_AddonMessage_HeaderColor"] = "Addon Messaging Header Color",
	["lang_Chat_AddonMessage_HeaderColor_tip"] = "Set the header color for addon messaging.",
	["lang_Chat_AddonMessage_MsgColor"] = "Addon Messaging Message Color",
	["lang_Chat_AddonMessage_MsgColor_tip"] = "Set the message color for addon messaging.",
	["lang_Chat_QuestInfo_HeaderColor"] = "Quest Info Header Color",
	["lang_Chat_QuestInfo_HeaderColor_tip"] = "Set the header color for addon messaging.",
	["lang_Chat_QuestInfo_MsgColor"] = "Quest Info Message Color",
	["lang_Chat_QuestInfo_MsgColor_tip"] = "Set the message color for quest information.",
	
	
	
	
	
	["lang_quests_timer_settings"] = "Quest Timer Settings",
	["lang_quests_timer_settings_Tip"] = "Enable/disable Quest Timer and set fonts and colors.",
	["lang_fcmqt_settings"] = "FCMQT Settings",
	["lang_global_settings"] = "Global Settings",
	
	["lang_language_settings"] = "Language",
	["lang_preset_settings"] = "Preset",
	["lang_quests_filtered_settings"] = "Show Quest Types",
	["lang_overall_transparency"] = "Overall Transparency",
	["lang_overall_width"] = "Overall Width",
	["lang_position_lock"] = "Lock Background Position",
	["lang_backgroundcolor_opt"] = "Enable Background Color",
	["lang_backgroundcolor_value"] = "Background Color",

	["lang_mouse_settings"] = "Mouse Controls Settings",
	["lang_mouse_1"] = "Mouse Left Button",
	["lang_mouse_2"] = "Mouse Center Button",
	["lang_mouse_3"] = "Mouse Right Button",
	["lang_mouse_4"] = "Mouse Button 4",
	["lang_mouse_5"] = "Mouse Button 5",

	["lang_timer_title_font"] = "Quest Timer Font",
	["lang_timer_title_font_tip"] = "Font for Quest Timer displayed on focus quests that have a timer.",
	["lang_timer_title_style"] = "Quest Timer Font Style",
	["lang_timer_title_style_tip"] = "Font style used onQuest Timer displayed on focus quests that have a timer.",
	["lang_timer_title_size"] = "Quest Timer Font Size",
	["lang_timer_title_size_tip"] = "Font size for Quest Timer displayed on focus quests that have a timer.",
	["lang_timer_title_color"] = "Queset Timer Font Color",
	["lang_timer_title_color_tip"] = "Font color for Quest Timer displayed on focus quests that have a ",
	
	["lang_area_settings"] = "Zones Quests Settings",
	["lang_area_name"] = "Show Quests Zone/Category Name",
	["lang_area_font"] = "Zone/Category Font",
	["lang_area_style"] = "Zone/Category Font Style",
	["lang_area_size"] = "Zone/Category Font Size",
	["lang_area_padding"] = "Zone/Category Padding Size",
	["lang_area_color"] = "Zone/Category Color",
	["lang_autohidequestzone_option"] = "Enable Auto Hide Zone",
	["lang_questzone_option"] = "Show Quests in Current Zone Only",
	["lang_quests_guild"] = "Show Guilds Quests",
	["lang_quests_mainstory"] = "Show Main Story Quests",
	["lang_quests_cyrodiil"] = "Show Cyrodiil Quests",

	["lang_quests_class"] = "Show Class Quests",
	["lang_quests_class_tip"] = "Toggle class quests being visible.",
	["lang_quests_crafting"] = "Show Crafting Quests",
	["lang_quests_crafting_tip"] = "Toggle crafting quests being visible.",
	["lang_quests_group"] = "Show Group Quests",
	["lang_quests_group_tip"] = "Toggle Group quests being visible.",
	["lang_quests_dungeon"] = "Show Dungeon Quests",
	["lang_quests_dungeon_tip"] = "Toggle dungeon quests being visible.",
	["lang_quests_raid"] = "Show Raid quests",
	["lang_quests_raid_tip"] = "Toggle Raid quests being visible.",
	["lang_quests_AVA"] = "Show AVA quests",
	["lang_quests_AVA_tip"] = "Toggle AVA Quests being visible.",
	["lang_quests_event"] = "Show Event/Holiday Quests",
	["lang_quests_event_tip"] = "Toggle Event/Holiday quests being visible.",
	["lang_quests_BG"] = "Show Battleground Quests",
	["lang_quests_BG_tip"] = "Toggle Battleground quests being visible.",
	["lang_area_hybrid"] = "Show Category Zone View",
	["lang_area_hybrid_tip"] = "Show zones in the classic Catefory view, example, Guild quests listed in its own category not the zone they are in.",

	["lang_no_trans_focused_zone"] = "Focused Quest Zone Transparency",
	["lang_no_trans_focused_zone_tip"] = "The zone or category the focused quest is in, will not use the Not Focused Transparency",
	
	["lang_quests_settings"] = "Quests Settings",
	["lang_quests_sort"] = "Sort Quests By...",
	["lang_quests_nb"] = "Displayed Quests",
	["lang_quests_show_timer"] = "Show Quest Timer",
	["lang_quests_show_timer_tip"] = "Show Quest Timer for the focused quest when there is a completion timer.  Please note a blank field will appear at the",
	
	

	["lang_quests_hide_obj"] = "Hide Objectives/Hints Except when Focused",
	["lang_quests_hide_obj_tip"] = "Hide the quest objectives and hints from all quests except on the focused quest.",
	
	["lang_quests_hide_obj_optional"] = "Hide Completed Hints and Objectives",
	["lang_quests_hide_obj_optional_tip"] = "Hide the quests optional objectives/hints that have been completed for all quests.",
	
	["lang_quests_level"] = "Show Quests Level",
	["lang_quests_optinfos"] = "Hide ALL Hints and Optional Info",
	["lang_quests_autoshare"] = "Auto Share Quests",
	["lang_quests_autountrack"] = "Auto Untrack Hidden Quests",
	["lang_icon_opt"] = "Enable Assisted Quest Icon",
	["lang_icon_texture"] = "Assisted Quest Icon Texture",
	["lang_icon_size"] = "Assisted Quest Icon Size",
	["lang_icon_color"] = "Assisted Quest Icon Color",
	["lang_quests_transparency_opt"] = "Enable Transparency for quests that are not focused.",
	["lang_quests_transparency"] = "Not Focused Quests Transparency",

	["lang_titles_settings"] = "Quest Name Settings",
	["lang_titles_font"] = "Quest Name Font",
	["lang_titles_style"] = "Quest Name Font Style",
	["lang_titles_size"] = "Quest Name Font Size",
	["lang_titles_padding"] = "Quest Name Padding Size",
	["lang_titles_default"] = "Default Quest Name Color",
	["lang_titles_custom"] = "Custom Titles Colors",
	["lang_titles_veasy"] = "Quest Name Color for Very Easy Quests",
	["lang_titles_easy"] = "Quest Name Color for Easy Quests",
	["lang_titles_normal"] = "Quest Name Color for Normal Quests",
	["lang_titles_hard"] = "Quest Name Color for Hard Quests",
	["lang_titles_vhard"] = "Quest Name Color for Very Hard Quests",

	["lang_obj_settings"] = "Objectives/Hints Settings",
	["lang_obj_font"] = "Objectives Font",
	["lang_obj_style"] = "Objectives Font Style",
	["lang_obj_size"] = "Objectives Font Size",
	["lang_obj_padding"] = "Objectives Padding Size",
	["lang_obj_color"] = "Objectives Font Color",
	["lang_obj_ccolor"] = "Completed Objectives Font Color",
	["lang_obj_optcolor"] = "Optional Objectives Font Color",
	["lang_obj_optccolor"] = "Completed Optional Objectives Font Color",

	["lang_infos_settings"] = "Infos Settings",
	["lang_infos_opt"] = "Show Infos",
	["lang_infos_font"] = "Infos Font",
	["lang_infos_style"] = "Infos Font Style",
	["lang_infos_size"] = "Infos Font Size",
	["lang_infos_color"] = "Infos Font Color",
	
	-- Menu tips
	["lang_language_settings_tip"] = "Set your language",
	["lang_preset_settings_tip"] = "Select a preset",
	["lang_overall_transparency_tip"] = "Change the global transparency",
	["lang_overall_width_tip"] = "Change the window width",
	["lang_position_lock_tip"] = "Lock/Unlock position and enable mouse actions",
	["lang_backgroundcolor_opt_tip"] = "Enable background color",
	["lang_backgroundcolor_value_tip"] = "Change the background color",
	
	["lang_mouse_1_tip"] = "Set an action for the left click",
	["lang_mouse_2_tip"] = "Set an action for the center click",
	["lang_mouse_3_tip"] = "Set an action for the right click",
	["lang_mouse_4_tip"] = "Set an action for the button 4",
	["lang_mouse_5_tip"] = "Set an action for the button 5",
	
	["lang_area_name_tip"] = "Enable the quest zone/category name to be displayed.",
	["lang_area_font_tip"] = "Set the font for the zone/category for the quest.",
	["lang_area_style_tip"] = "Set the font style for the zone/category for the quest",
	["lang_area_size_tip"] = "Change the font size for the zone/category for the quest",
	["lang_area_padding_tip"] = "Change the left and right padding size for the zone/category for the quest",
	["lang_area_color_tip"] = "Change the color for the zone/category for the quest",
	["lang_autohidequestzone_option_tip"] = "Follow the focused quest and hide others zone/category for the quest",
	["lang_questzone_option_tip"] = "Show quests in the current zone/category for the focused quest",
	["lang_quests_guild_tip"] = "Show guilds quests",
	["lang_quests_mainstory_tip"] = "Show main story quests",
	["lang_quests_cyrodiil_tip"] = "Show Cyrodiil quests",

	["lang_quests_sort_tip"] = "Set the order for quests",
	["lang_quests_nb_tip"] = "Change the number of quest displayed",
	["lang_quests_show_quest_timer_tip"] = "Show timer for timed quests",
	["lang_quests_level_tip"] = "Show quests level",
	["lang_quests_optinfos_tip"] = "Hide hidden infos/hints for all quests, including focused quest.",
	["lang_quests_autoshare_tip"] = "Enable the quest auto share when you are in group",
	["lang_quests_autountrack_tip"] = "Untrack on the compass all hidden quests",
	["lang_icon_opt_tip"] = "Enable the quest icon",
	["lang_icon_texture_tip"] = "Set the icon for the current assisted quest",
	["lang_icon_size_tip"] = "Change the icon size",
	["lang_icon_color_tip"] = "Change the color for the quest icon",
	["lang_quests_transparency_opt_tip"] = "Enable the transparency for other quests than the focused quest",
	["lang_quests_transparency_tip"] = "Change the transparency of quests that are not focused.",

	["lang_titles_font_tip"] = "Set the font for the quest names",
	["lang_titles_style_tip"] = "Set the font style the quest names",
	["lang_titles_size_tip"] = "Change the font size for quest names",
	["lang_titles_padding_tip"] = "Change the left and right padding size for quest names",
	["lang_titles_default_tip"] = "Change the color of quest names",
	["lang_titles_custom_tip"] = "Enable changing color from player level",
	["lang_titles_veasy_tip"] = "Change the color of quest names < level - 4",
	["lang_titles_easy_tip"] = "Change the color of quest names <= level - 2",
	["lang_titles_normal_tip"] = "Change the color of quest names = level +- 1",
	["lang_titles_hard_tip"] = "Change the color of quest names >= level + 2",
	["lang_titles_vhard_tip"] = "Change the color of quest names > level + 4",	
	
	["lang_obj_font_tip"] = "Set the font for the quest text",
	["lang_obj_style_tip"] = "Set the font style the quest text",
	["lang_obj_size_tip"] = "Change the font size for quest text",
	["lang_obj_padding_tip"] = "Change the left and right padding size for quest text",
	["lang_obj_color_tip"] = "Change the color of quest text",
	["lang_obj_ccolor_tip"] = "Change the color of the completed objectives text",
	["lang_obj_optcolor_tip"] = "Change the color of optional quest text",
	["lang_obj_optccolor_tip"] = "Change the color of the completed optional objectives text",

	["lang_infos_opt_tip"] = "Display total of current quests",
	["lang_infos_font_tip"] = "Set the font for informations",
	["lang_infos_style_tip"] = "Set the font style for informations",
	["lang_infos_size_tip"] = "Change the font size for informations",
	["lang_infos_color_tip"] = "Change the font color for informations",
	
	-- Menu Warn
	["lang_menu_warn_1"] = "|c8B1E1E Change this option will reload the UI",
	["lang_menu_warn_2"] = "|c8B1E1E Change this option will reload the UI and overwrites your current settings",

	-- Quests Infos
	["quest_optional"] = "Optional",
	["quest_hint"] = "Hint",	
	["quest_hiddenhint"] = "Hidden Hint",
	
	["lang_tracker_type_guild"] = "Guild",
	["lang_tracker_type_mainstory"] = "Main Story",
	["lang_tracker_type_dungeon"] = "Dungeon",
	["lang_tracker_type_class"] = "Class",
	["lang_tracker_type_craft"] = "Craft",
	["lang_tracker_type_group"] = "Group",
	
	["lang_tracker_type_holiday_event"] = "Holiday Event",
	["lang_tracker_type_raid"] = "Raid",
	["lang_tracker_type_bg"] = "Battle Ground",
	["lang_tracker_type_qa_test"] = "Test",
	
	-- Mouse Interactions
	["lang_mouse_ctrl_assisted"] = "Change Assisted Quest",
	["lang_mouse_ctrl_filterzone"] = "Filter by Current Zone",
	["lang_mouse_ctrl_share"] = "Share a Quest",
	["lang_mouse_ctrl_showmap"] = "Show on Map",
	["lang_mouse_ctrl_remove"] = "Remove a Quest",
	
	-- Console
	["lang_console_autoshare"] = "You auto share a quest",
	["lang_console_share"] = "You share a quest",
	["lang_console_noshare"] = "This quest is not shareable",
	["lang_console_abandon"] = "Abandon quest",
}